### ISSUE TITLE
打包后字符串中的中文被转义

### ISSUE THREAD

**Issue by h46incon** [lisonge/vite-plugin-monkey#10]
如以下 js 代码：
```js
ClickSelector('button', '确认')
```

在打包后会变成：
```js
ClickSelector("button", "\u786E\u8BA4");
```

用倒是能用，但是在油猴插件中直接查看代码的时候就看不懂写的是什么了。

**Comment by lisonge** [comment]
这是 vite/rollup 编译的，不是 vite-plugin-monkey 导致的

**Comment by lisonge** [comment]
我刚刚 Google 了一下，没找到配置这个的方法
你可以去 <https://github.com/rollup/rollup/issues> 或者 <https://github.com/vitejs/vite/issues>

**Comment by h46incon** [comment]
我问这个就是我有查看的需要。我试了下 webpack 打包是没这个问题的，我尝试使用 webpack 吧

**Comment by lisonge** [comment]
@h46incon 

找到了，是 esbuild 干的，解决方法如下

```ts
import { defineConfig } from 'vite';

export default defineConfig({
    esbuild:{
        charset:'utf8'
    }
});

```

**Comment by h46incon** [comment]
TQL了，我当时也找了好久没找到，非常感谢
