### ISSUE TITLE
请求支持脚本猫的用户配置

### ISSUE THREAD

**Issue by HoshinoRei** [lisonge/vite-plugin-monkey#103]
[用户配置](https://docs.scriptcat.org/docs/dev/config/) 的内容在 `==UserScript==` 的后面。小玲翻了 `vite-plugin-monkey` 的 `index.d.ts` 文件，实在找不到能在 `==UserScript==` 后添加自定义内容的功能。

**Comment by lisonge** [comment]
released in v3.5.0

<https://github.com/lisonge/vite-plugin-monkey/blob/149267849d61c8ce7b50c0163ea6183a3ed1ee6a/playground/mini-css/vite.config.ts#L6-L12>

**Comment by HoshinoRei** [comment]
> released in v3.5.0
> 
> https://github.com/lisonge/vite-plugin-monkey/blob/149267849d61c8ce7b50c0163ea6183a3ed1ee6a/playground/mini-css/vite.config.ts#L6-L12

感谢添加！
