### ISSUE TITLE
无法正确注入css

### ISSUE THREAD

**Issue by andywang425** [lisonge/vite-plugin-monkey#104]
当脚本的`@run-at`为`document-start`时`document.head`可能为`null`。我的环境是Windows 10，Chrome 116.0.5845.141，Tampermonkey v4.19.0。当我在Tampermonkey的设置->实验里把`注入模式`改成`及时`之后，用`ctrl+F5`刷新页面就能稳定复现这个bug。有些用户跟我反馈说他们在注入模式是默认的时候也会出这个问题。

日志：
![image](https://github.com/lisonge/vite-plugin-monkey/assets/56548456/54f7f5cb-d239-4107-93f4-2f664d2045a4)
![image](https://github.com/lisonge/vite-plugin-monkey/assets/56548456/ccb9b7b5-7742-4b32-821c-90625bc5505d)

我试着把开头那段注入css的代码改成`GM_addStyle`注入，不报错而且css能被正确注入。
![image](https://github.com/lisonge/vite-plugin-monkey/assets/56548456/524af780-c79b-49e0-84e4-e5df92dc4406)

修改后的代码：
![image](https://github.com/lisonge/vite-plugin-monkey/assets/56548456/f0094e3e-0499-40d3-87bb-f6845187175c)

日志（后面的`cssLoader`还是报错了）：
![image](https://github.com/lisonge/vite-plugin-monkey/assets/56548456/47aa7e6f-988d-4aba-8340-6c94f5e954b0)
![image](https://github.com/lisonge/vite-plugin-monkey/assets/56548456/79278b2a-61ce-44b6-bd95-d6fc2a844169)

我感觉把改为使用`GM_addStyle`注入css似乎可行，不知道作者有什么好的解决办法？

下面是我刚刚查资料时找到的一些链接，希望能有帮助。

其它项目里一些相关的issue：
https://github.com/violentmonkey/violentmonkey/issues/1292
https://github.com/greasemonkey/greasemonkey/issues/2515

Bilibili-Evolved这个脚本会等head出现后再执行其它逻辑：
https://github.com/the1812/Bilibili-Evolved/blob/c14a2332244f88f8c749305b7279601f21833456/src/client/init.ts#L26-L29

**Comment by lisonge** [comment]
released in v3.5.0

<https://github.com/lisonge/vite-plugin-monkey/blob/149267849d61c8ce7b50c0163ea6183a3ed1ee6a/packages/vite-plugin-monkey/src/node/types.ts#L303-L331>

<https://github.com/lisonge/vite-plugin-monkey/blob/149267849d61c8ce7b50c0163ea6183a3ed1ee6a/packages/vite-plugin-monkey/src/node/plugins/externalLoader.ts#L4-L25>

**Comment by andywang425** [comment]
感谢修复
