### ISSUE TITLE
能否支持多个脚本同时开发？

### ISSUE THREAD

**Issue by looch** [lisonge/vite-plugin-monkey#106]
通常用户脚本都比较小，在一个目录里同时管理多个脚本是常见的开发方式。

**Comment by lisonge** [comment]
在一个 vite 实例里开发多个脚本，这个是不支持的，因为每个脚本的名称和 grant 以及依赖库都不一样

但是每个脚本其实就是一个项目/包，在一个仓库管理多个项目可以使用 pnpm monorepo

当前项目就是一个简单的 pnpm+monorepo，所有示例脚本都在 [playground](https://github.com/lisonge/vite-plugin-monkey/tree/main/playground)，它们可以共用 workspace 的依赖
