### ISSUE TITLE
Suggestion: tell users that viteConfig.build.minify is disabled by default in documentation

### ISSUE THREAD

**Issue by XiaoSong-CPE** [lisonge/vite-plugin-monkey#107]
Without chunk rendering and minifying, the size of the resulting user script is horribly large. I think many users would like to know that `viteConfig.build.minify` is disabled by default in the documentation. I myself thought it was a compatibility issue at first, until I know it is just because of greasyfork's policy at #85. It's confusing, so I suggest to let everyone know it in the documentation.

**Comment by lisonge** [comment]
<https://github.com/lisonge/vite-plugin-monkey/commit/d17f9b73744ffef7d9b02b2280064b54d868d7ba>
