### ISSUE TITLE
引入css文件压缩问题

### ISSUE THREAD

**Issue by Ouka2020** [lisonge/vite-plugin-monkey#11]
如图：
![image](https://user-images.githubusercontent.com/36848100/184065131-6f70a083-7e75-45c2-ba0f-745d0c34634e.png)
![image](https://user-images.githubusercontent.com/36848100/184065432-334d6ed7-81fd-4dbe-922c-7263bfc3a28e.png)

引入css后，生成的脚本文件的css样式为一串字符串，压缩一下是否更好呢。
![image](https://user-images.githubusercontent.com/36848100/184065520-cf105f72-85bd-4504-80cb-7257e740d4b8.png)

**Comment by lisonge** [comment]
<https://github.com/lisonge/vite-plugin-monkey/blob/c00974c7bff92f33015f7fdc3f2a1721ffd65d88/playground/example/vite.config.ts#L37-L38>
