### ISSUE TITLE
在同一目录下创建多个 vite.config.xx.ts 

### ISSUE THREAD

**Issue by panghujiajia** [lisonge/vite-plugin-monkey#111]
在同一目录下创建多个 vite.config.xx.ts 即可

vite.config.script1.ts 
```shell
vite --config vite.config.script1.ts 
```

vite.config.script2.ts
```shell
vite --config vite.config.script2.ts 
```
关于项目多脚本开发打包的问题，能否将配置这块处理一下？例如单个vite文件，里面配置多个脚本配置

**Comment by lisonge** [comment]
> 例如单个vite文件，里面配置多个脚本配置

在单个仓库里开发多个脚本，我建议使用 monorepo 或者多个 vite.config.ts 文件

---

如果只想是在单个 ts 文件里打包构建多个脚本，可以参考 <https://github.com/lisonge/vite-plugin-monkey/issues/47#issuecomment-1449196967>
