### ISSUE TITLE
elementplus打包后运行时报没有createElementVnode的错误

### ISSUE THREAD

**Issue by 1229984599** [lisonge/vite-plugin-monkey#114]
在开发模式时能够正常运行，打包后将代码复制到油猴就开始报错了。使用preview的方式也还是要报错

**Comment by lisonge** [comment]
解决方法应该是 cdn 链接后面应该附加一个 dataUri 脚本把 vue 挂载到 window 上能让 elementplus 访问到就行

**Comment by 1229984599** [comment]
> 解决方法应该是 cdn 链接后面应该附加一个 dataUri 脚本把 vue 挂载到 window 上能让 elementplus 访问到就行

对头，怪我没有看清楚readme那里有，一直在issue里面搜索，非常感谢作者的插件，现在写油猴简直太爽了。另外想请教一个问题，我运行时vueDemi也会报未定义，还是需要这种方式操作吗？我当时用的最笨的办法，在油猴里面加上了vueDemi的库

**Comment by lisonge** [comment]
> 我运行时vueDemi也会报未定义，还是需要这种方式操作吗？

对于一些库如 pinia ，它的依赖里是有 vue-demi 的，如果你将 pina 打包进去，那就不需要配置 vue-demi 的 cdn 链接

但是 pinia 的 iife 格式的库里没有 vue-demi，如果你对 pinia 使用 cdn 排除，也就是使用 iife 格式，那么就需要处理 pinia 的 iife 格式访问 vue-demi 的问题

一般来说有两种方法

- 如果你用的库的 cdn 没有特别依赖 vue 的版本，只需要将 VueDemi 简单指向 Vue 即可，也就是在 vue cdn 链接后面添加 `util.dataUrl('window.VueDemi=Vue')`
- 或者直接在 vue cdn 链接后面加上 `https://cdn.jsdelivr.net/npm/vue-demi@latest/lib/index.iife.js`

**Comment by 1229984599** [comment]
> > 我运行时vueDemi也会报未定义，还是需要这种方式操作吗？
> 
> 对于一些库如 pinia ，它的依赖里是有 vue-demi 的，如果你将 pina 打包进去，那就不需要配置 vue-demi 的 cdn 链接
> 
> 但是 pinia 的 iife 格式的库里没有 vue-demi，如果你对 pinia 使用 cdn 排除，也就是使用 iife 格式，那么就需要处理 pinia 的 iife 格式访问 vue-demi 的问题
> 
> 一般来说有两种方法
> 
> * 如果你用的库的 cdn 没有特别依赖 vue 的版本，只需要将 VueDemi 简单指向 Vue 即可，也就是在 vue cdn 链接后面添加 `util.dataUrl('window.VueDemi=Vue')`
> * 或者直接在 vue cdn 链接后面加上 `https://cdn.jsdelivr.net/npm/vue-demi@latest/lib/index.iife.js`

非常感觉大佬您的解答，可否贴个赞赏码出来呀，金额不多，只是想表达一下自己的谢意。确实感觉你的项目让我用着非常爽，希望能够坚持下去

**Comment by lisonge** [comment]
如果您撅得这个开源免费的软件**帮助到了您**, 并且您想通过捐赠支持这个项目, 那么可以通过以下方式捐赠

|                                                                                             |                                                                                             |
| ------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------- |
| ![img](https://github.com/gkd-kit/gkd/assets/38517192/6ac189ff-1b8d-4de9-9fae-104dd9b295cd) | ![img](https://github.com/gkd-kit/gkd/assets/38517192/0d35c9cc-9868-4028-b159-fd8e58ed3998) |

**Comment by 1229984599** [comment]
> 如果您撅得这个开源免费的软件**帮助到了您**, 并且您想通过捐赠支持这个项目, 那么可以通过以下方式捐赠
> 
> ![img](https://user-images.githubusercontent.com/38517192/281307074-6ac189ff-1b8d-4de9-9fae-104dd9b295cd.png)	![img](https://user-images.githubusercontent.com/38517192/281307103-0d35c9cc-9868-4028-b159-fd8e58ed3998.jpg)
👌微信已经发过去了

**Comment by lisonge** [comment]
嗯嗯，已收到了，谢谢打赏
