### ISSUE TITLE
引用根目录以外的文件，dev时不报错，build时会报错

### ISSUE THREAD

**Issue by zyronon** [lisonge/vite-plugin-monkey#123]
![image](https://github.com/lisonge/vite-plugin-monkey/assets/19986642/b52ccab9-751b-4a2f-8e11-2b0675506925)

如图所示，我有一个项目，原来是运行在pc上，现在要兼容手机网页，我打算新建一个项目，把两个项目共同的内容提取出来放到了根目录平级的core目录里面。dev时不报错，build时会报错

**Comment by lisonge** [comment]
这错误不是很明显吗？ 根据 js 模块规范 core/core.ts 本来不能 import `$` 这个包

最简单发方法是将你的 <https://github.com/zyronon/web-scripts/blob/fb742ebeb67defd19108b5b498ade3c5baff59a3/v2next/core/core.ts#L2>

换成 
```ts
import {GM_openInTab} from "../pc/node_modules/vite-plugin-monkey/dist/client";
```

此外你这个包结构最好用 monorepo，将 `vite-plugin-monkey` 等共有的包装在根路径

**Comment by zyronon** [comment]
谢谢大佬，改成monorepo解决问题了。另外请问大佬，为什么不能通过本机ip访问呢，只能通过127.0.0.1。我想手机调试不知道怎么弄了

**Comment by lisonge** [comment]
如果你想要设置多个 ip 访问

设置 viteConfig.server.host 为 0.0.0.0 即可

点击控制台出现的地址即可安装

**Comment by zyronon** [comment]
好的好的，谢谢大佬
