### ISSUE TITLE
[Feature Request] 本地图标加载

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [lisonge/vite-plugin-monkey#126]
是否可以提供一些引入本地图标的方式

比如 public 目录下的 logo.svg
转换成 `data:image/svg+xml;base64,` 的格式

虽然可以手动转换 但是想想让框架支持或许会更好一些 (?

**Comment by lisonge** [comment]
一个普通的 vite 插件就能做的事情，没必要增加维护成本
