### ISSUE TITLE
脚本猫， 后台脚本不支持嘛？

### ISSUE THREAD

**Issue by Hunlongyu** [lisonge/vite-plugin-monkey#128]
https://docs.scriptcat.org/docs/dev/backgroud/

脚本猫独有的后台脚本，在  vite.config.js 里配置 crontab 和  background· 属性声明，在构建后，会丢失。

导致 无法正常运行。

希望能加上~ 感谢~🥹

**Comment by lisonge** [comment]
首先脚本猫的后台脚本不是合法语法的 js 模块，其次不支持动态加载模块，无法支持

![image](https://github.com/lisonge/vite-plugin-monkey/assets/38517192/ed823781-ef2d-4ccb-9289-d13dd64d2527)
