### ISSUE TITLE
是否可以在 vite-plugin-monkey/dist/client 中导出更多内部类型以便于 ts 开发

### ISSUE THREAD

**Issue by Tsuk1ko** [lisonge/vite-plugin-monkey#13]
例如我需要获取 `GM_xmlhttpRequest` 参数中 `responseType` 的类型，目前只能这么写

```
Parameters<typeof GM_xmlhttpRequest>['0']['responseType']
```

但如果有导出类型 `XhrRequest`，就可以简化成

```
XhrRequest['responseType']
```

**Comment by lisonge** [comment]
很有道理，我一会发个版本

**Comment by lisonge** [comment]
fix: by [v2.0.1/CHANGELOG.md#201-features](https://github.com/lisonge/vite-plugin-monkey/blob/v2.0.1/packages/vite-plugin-monkey/CHANGELOG.md#201-features)

sample
```ts
import type { MonkeyWindow, XhrRequest } from '$';
type ScriptInfo = MonkeyWindow['GM_info']; // if you want
```
