### ISSUE TITLE
React dev tools chrome extension

### ISSUE THREAD

**Issue by Thorvarium** [lisonge/vite-plugin-monkey#137]
Is this supported? Doesn't matter what I do, I can't make the components and profiler tabs to load

**Comment by lisonge** [comment]
```shell
pnpm create monkey
# choose react-ts
cd react-ts
pnpm i
pnpm dev
```

![img](https://github.com/lisonge/vite-plugin-monkey/assets/38517192/7aba620c-b7bd-4c7d-82e4-a350a7edf35e)

are there any other questions ?

**Comment by Thorvarium** [comment]
> ```shell
> pnpm create monkey
> # choose react-ts
> cd react-ts
> pnpm i
> pnpm dev
> ```
> 
> ![img](https://private-user-images.githubusercontent.com/38517192/309548721-7aba620c-b7bd-4c7d-82e4-a350a7edf35e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MDc3NzQsIm5iZiI6MTcwOTUwNzQ3NCwicGF0aCI6Ii8zODUxNzE5Mi8zMDk1NDg3MjEtN2FiYTYyMGMtYjdiZC00YzdkLTgyZTQtYTM1MGE3ZWRmMzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDIzMTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NjI2OTk0YWQ2MTM3YjljNDFkMDE2ZDUyYjAwYjY3M2ViM2NhMjA2OTNmMDQxNDE5NzRjNzc5MjYzMmIxNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nrLzka32QcP6GknEFsXuCATEZ5RSEwDfo5lv0aNPweI)
> 
> are there any other questions ?

Thanks for the fast reply. It does work on a new project. I will keep messing around my project to see if I can make it work too.

That is all! thanks
