### ISSUE TITLE
Uncaught TypeError: hmrClient.dataMap.has is not a function

### ISSUE THREAD

**Issue by lcandy2** [lisonge/vite-plugin-monkey#139]
Uncaught TypeError: hmrClient.dataMap.has is not a function
    at new HMRContext (hmr.ts:41:28)
    at createHotContext (client.ts:425:10)
    at app.css:1:96

![CleanShot 2024-03-11 at 11 26 35@2x](https://github.com/lisonge/vite-plugin-monkey/assets/45784494/830ed5a8-e818-4a34-b9b3-098b596fd68a)

![CleanShot 2024-03-11 at 11 27 36@2x](https://github.com/lisonge/vite-plugin-monkey/assets/45784494/2a73933a-2664-4aed-a7c9-9189ed81cb06)

![CleanShot 2024-03-11 at 11 36 41@2x](https://github.com/lisonge/vite-plugin-monkey/assets/45784494/d03b15f9-db60-43d6-b1f7-b8f720fbb544)

这是create monkey的模板，仅修改vite config中的match内容，编译安装后问题解决，但无法dev调试。

**Comment by lisonge** [comment]
`Uncaught TypeError: hmrClient.dataMap.has is not a function`

应该是你的宿主网站的有一个叫 Map 的全局函数占用了引用，导致 vite 这边使用的不是 js 原生的 Map 而报错

**Comment by lcandy2** [comment]
这个宿主网站是学习通🤣，这种情况下，有没有什么好的dev方法，还是只能build

**Comment by lisonge** [comment]
```ts
import { defineConfig } from 'vite';
import monkey from 'vite-plugin-monkey';

export default defineConfig({
  plugins: [
    {
      name: 'force-polyfill',
      apply: 'serve',
      transform(code, id, options) {
        if (code.includes('Map(')) {
          // pnpm add core-js-pure
          return code + '\n' + `import Map from 'core-js-pure/actual/map';`;
        }
      },
    },
    monkey({
      entry: 'src/main.tsx',
      userscript: {
        icon: 'https://vitejs.dev/logo.svg',
        namespace: 'npm/vite-plugin-monkey',
        match: ['https://www.google.com/'],
      },
    }),
  ],
});
```

你可以使用上面简单的插件来强制覆盖引用标识，但是这个只是简单的处理

如果源代码本来就有类似 `const Map = xxx`  就会报错，这时候可以简单过滤 id 直接 return

**Comment by lisonge** [comment]
你可以搜索如何在 vite 里使用 cjs 优化依赖解决

**Comment by lcandy2** [comment]
I searched for core-js issues about how to use core-js as cjs in a type module, and one of the replies mentioned the simplest option, "Use <script>".

So, in my case, it was only the dev that didn't work anyway, and the build is totally fine, so I end up by creating a new UserScript below.

```
// ==UserScript==
// @name         Fix modified browser native function.
// @namespace    http://tampermonkey.net/
// @match        *://*/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    const script = document.createElement('script');
    script.src = 'https://cdn.jsdelivr.net/npm/core-js-bundle@3.36.0/minified.min.js';
    document.head.append(script);

})();
```

Anyway, thanks for pointing the problem about Map function and super fast reply!

**Comment by lisonge** [comment]
刚才的代码有点问题，正确的代码应该是下面这种

```ts
import { defineConfig } from 'vite';
import monkey from 'vite-plugin-monkey';
import MagicString from 'magic-string';

export default defineConfig({
  plugins: [
    {
      name: 'force-polyfill',
      apply: 'serve',
      transform(code, id, options) {
        if (id.includes('core-js-pure')) return;
        if (code.includes('Map(')) {
          const s = new MagicString(code);
          s.prepend(`import Map from 'core-js-pure/actual/map';\n`);
          return { code: s.toString(), map: s.generateMap() };
        }
      },
    },
    monkey({
      entry: 'src/main.tsx',
      userscript: {
        icon: 'https://vitejs.dev/logo.svg',
        namespace: 'npm/vite-plugin-monkey',
        match: ['https://www.google.com/'],
      },
    }),
  ],
  optimizeDeps: {
    include: ['core-js-pure/actual/map'],
  },
});

```
