### ISSUE TITLE
include 配置直接使用正则表达式时输出缺少首尾斜杠

### ISSUE THREAD

**Issue by Tsuk1ko** [lisonge/vite-plugin-monkey#14]
例如 `include: /^xxx$/` 输出获得 `// @include ^xxx$`，是错误的，应当输出  `// @include /^xxx$/` 

https://www.tampermonkey.net/documentation.php#_include

**Comment by lisonge** [comment]
确实，我在代码里是直接使用
```js
attrList​.​push​(​[​k​,​ ​v​.​source​]​)​;
```
谢谢提醒，后面我修改一下

**Comment by lisonge** [comment]
fix by [v2.0.1/CHANGELOG.md#201-bugfixes](https://github.com/lisonge/vite-plugin-monkey/blob/v2.0.1/packages/vite-plugin-monkey/CHANGELOG.md#201-bugfixes)
