### ISSUE TITLE
[Bug] GM is not defined

### ISSUE THREAD

**Issue by zhuozhiyongde** [lisonge/vite-plugin-monkey#142]
```js
GM.xmlHttpRequest({
    method: 'GET',
    url: downloadLink,
    responseType: 'blob',
    onload: function (response) {
        const blob = response.response;
        const url = URL.createObjectURL(blob); // 为Blob对象创建一个临时URL
        const a = document.createElement('a'); // 创建一个a标签
        a.href = url;
        a.download = fileName;
        document.body.appendChild(a); // 将a标签添加到文档中
        a.click(); // 模拟点击a标签以触发下载
        document.body.removeChild(a); // 下载后移除a标签
        URL.revokeObjectURL(url); // 释放URL对象
    },
    onerror: function (err) {
        console.error(err);
    },
});
```

以上是脚本 main.js 内容，已经开了授权（自动开启的），但是无效。

**Comment by zhuozhiyongde** [comment]
即使改变 API，依旧报错：

ReferenceError: GM_xmlhttpRequest is not defined

**Comment by zhuozhiyongde** [comment]
测试平台：chrome，tampermonkey

**Comment by lisonge** [comment]
你最好先查看文档了解如何正确使用 GM api

而不是直接发 issue

**Comment by zhuozhiyongde** [comment]
抱歉，可能是我表述的不清楚

是这样的，我在开发 dev 模式下确实无法使用这个 API，无论是现在这种写法还是 GM_xmlHttpRequdst 都不行，但是同样的代码我直接不打包放入一个新的脚本，却能正常工作。这让我感到很迷惑，所以来此提问orz

**Comment by lisonge** [comment]
你好，你确定你是按照文档里的 [写法](https://github.com/lisonge/vite-plugin-monkey/blob/main/README_zh.md#gm_api-%E7%94%A8%E6%B3%95)
```ts
import { GM_cookie, unsafeWindow, monkeyWindow, GM_addElement } from '$';
```
这样引入之后仍然报错吗

**Comment by zhuozhiyongde** [comment]
我使用了 
![image](https://github.com/lisonge/vite-plugin-monkey/assets/36695271/56efe080-330c-42f5-9e87-2a66f9a8b2f3)
这个写法，仍然报错
![image](https://github.com/lisonge/vite-plugin-monkey/assets/36695271/a5090ef6-58db-4c2c-9837-f8733d040efa)

**Comment by zhuozhiyongde** [comment]
![image](https://github.com/lisonge/vite-plugin-monkey/assets/36695271/5730da02-5462-4e14-859b-26745625764e)

**Comment by zhuozhiyongde** [comment]
这个是换了那个引入写法之后依然报错

**Comment by lisonge** [comment]
麻烦上传一个最小复现的 demo.zip 看看

**Comment by zhuozhiyongde** [comment]
![image](https://github.com/lisonge/vite-plugin-monkey/assets/36695271/7bca9e9d-a7ee-4524-a89a-53e83afc930f)

使用最新的 pnpm create monkey 直接创建然后修改的结果

**Comment by zhuozhiyongde** [comment]
[vite-plugin-monkey-bug.zip](https://github.com/lisonge/vite-plugin-monkey/files/14734511/vite-plugin-monkey-bug.zip)

**Comment by lisonge** [comment]
![image](https://github.com/lisonge/vite-plugin-monkey/assets/38517192/a93046f2-3a2b-4d4a-93f7-1d937980c358)

看起来是你的浏览器扩展的问题

**Comment by zhuozhiyongde** [comment]
我是用的是最新的 5.1.0 的 TamperMonkey

**Comment by lisonge** [comment]
> ![image](https://private-user-images.githubusercontent.com/36695271/316284799-5730da02-5462-4e14-859b-26745625764e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNTg5NTEsIm5iZiI6MTcxMTI1ODY1MSwicGF0aCI6Ii8zNjY5NTI3MS8zMTYyODQ3OTktNTczMGRhMDItNTQ2Mi00ZTE0LTg1OWItMjY3NDU2MjU3NjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA1MzczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNmZiOTRmZDhmZWM4NDRhNzQ5Y2VjZDNiNGU3MTkwYWRiZTk2YmQyMWExMzRhNDcyMGEzYjgxZGFmMTBhMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E4VOPgrpxbXxuPWO3-_zi1ny_bw80KDXHUVLgEe-Z1s)

这个是符合预期的，因为正确的变量名是 `GM_xmlhttpRequest` 不是 `GM_xmlHttpRequest`

**Comment by lisonge** [comment]
我不知道为什么脚本作用域的 window 上现在无法动态获取到 GM_api 了，看起来和 https://github.com/Tampermonkey/tampermonkey/issues/1567 相关

你的问题可以通过如下的代码暂时解决

```ts
import { defineConfig } from 'vite';
import monkey from 'vite-plugin-monkey';

export default defineConfig({
  plugins: [
    monkey({
      entry: 'src/main.tsx',
      userscript: {
        icon: 'https://vitejs.dev/logo.svg',
        namespace: 'npm/vite-plugin-monkey',
        match: ['https://www.google.com/'],
      },
      format: {
        generate(uOptions) {
          if (uOptions.mode == 'serve') {
            return (
              uOptions.userscript +
              '\n' +
              ['unsafeWindow', 'GM', 'GM_xmlhttpRequest'] // your userscript API from window
                .map((v) => `unsafeWindow.${v}=${v}`)
                .join(';\n')
            );
          }
          return uOptions.userscript;
        },
      },
    }),
  ],
});
```

**Comment by lisonge** [comment]
https://github.com/lisonge/vite-plugin-monkey/releases/tag/v3.5.2

**Comment by zhuozhiyongde** [comment]
感谢大佬，最新版已经可用。

**Comment by zikkurat** [comment]
大佬，解决了没有哇？！
使用最新版了，v3.5.2
用的是Violentmonkey(暴力猴)
输出：[vite-plugin-monkey] mount 0/25 GM_api to unsafeWindow
