### ISSUE TITLE
[功能请求] 增加一个输出 .meta.js 的构建选项

### ISSUE THREAD

**Issue by Tsuk1ko** [lisonge/vite-plugin-monkey#15]
`.meta.js` 只会包含 UserScript 注释，不包含代码正文，Tampermonkey 等脚本插件会自动使用该文件检查脚本更新而不必下载完整脚本，Greasy Fork 等脚本托管网站也会自动提供该文件（可以随便找个脚本链接把 `.user.js` 替换为 `.meta.js` 访问看看）

如果是使用 Github Pages 等托管脚本的话，自动生成 `.meta.js` 会很有用

**Comment by lisonge** [comment]
原来还有这种，可以

**Comment by lisonge** [comment]
finished by <https://github.com/lisonge/vite-plugin-monkey/blob/v2.1.1/packages/vite-plugin-monkey/CHANGELOG.md#211-features>

```json5
{
  build: {
    metaFileName:true, // 默认为 false，需要手动开启
    // or
    metaFileName: 'xxx.meta.js',
  }
}
```
