### ISSUE TITLE
使用`unplugin-vue-components`会导致`externalGlobal`失效

### ISSUE THREAD

**Issue by yzqdev** [lisonge/vite-plugin-monkey#152]
## 具体操作

我的vite配置 https://github.com/yzqbugs/monkey-bug/blob/main/vite.config.ts
不使用
```
import { ElMessageBox ,ElButton,ElDialog} from 'element-plus'
```

导入(见`App.vue`)

`pnpm build`则会生成一个不带ElementPlus的`monkey-bug.user.js`,大小为`202.07 kB`,并且,这个use.js内部会添加`ElMessageBox ,ElButton,ElDialog`的代码,即elemen-plus没有使用cdn

如下面的图片,打包出来,没有element-plus的exportVarName(ElementPlus)

![](https://raw.githubusercontent.com/yzqbugs/monkey-bug/main/bug.png)

## 如何使external生效?

此时,把`App.vue`里面的

```
//import { ElMessageBox ,ElButton,ElDialog} from 'element-plus'
```

注释去掉,重新打包,体积为`3.39 kB`

搜了`unplugin-vue-components`的issue,貌似不是`unplugin-vue-components`的原因

https://github.com/unplugin/unplugin-vue-components/issues?q=external

**Comment by lisonge** [comment]
1. update vite-plugin-monkey version to `4.0.0-alpha.1` in package.json
2. update field `element-plus` to `element-plus/es` in vite.config.ts

```diff
- "element-plus": cdn.npmmirror(
+ "element-plus/es": cdn.npmmirror(
```

**Comment by lisonge** [comment]
Is this problem solved?

**Comment by yzqdev** [comment]
Now it works well, thank you!

> 1. update vite-plugin-monkey version to `4.0.0-alpha.1` in package.json
> 2. update field `element-plus` to `element-plus/es` in vite.config.ts
> 
> ```diff
> - "element-plus": cdn.npmmirror(
> + "element-plus/es": cdn.npmmirror(
> ```

**Comment by lisonge** [comment]
https://github.com/lisonge/vite-plugin-monkey/releases/tag/v4.0.0
