### ISSUE TITLE
安装的server:xxx脚本无法把__vite-plugin-monkey.entry.js的script元素挂载到document.head元素上

### ISSUE THREAD

**Issue by WhiteSevs** [lisonge/vite-plugin-monkey#157]
## 环境
浏览器：[百分浏览器](https://static.centbrowser.cn/win_stable/5.1.1130.82/centbrowser_5.1.1130.82_x64_portable.exe)
扩展：篡改猴(5.1.1)

```js
@match https://www.douyin.com/search/*
@run-at document-start
```

## 截图

![02b972dc318da5804e200962c10cca01](https://github.com/lisonge/vite-plugin-monkey/assets/50544447/158a6eff-9a61-4dd3-b189-3464bd528af7)

![8b0c66398b39976b06778d9a39de190e](https://github.com/lisonge/vite-plugin-monkey/assets/50544447/63802f2b-77cf-4aed-8627-74e74bb5dade)

**Comment by lisonge** [comment]
使用 chrome 是否出现此问题？

**Comment by lisonge** [comment]
那就是 百分浏览器 的问题了，你换 chrome 就行

**Comment by WhiteSevs** [comment]
ok，还有其他问题在讨论区了，麻烦大佬看看是某可以解决😄
https://github.com/lisonge/vite-plugin-monkey/discussions/165

**Comment by WhiteSevs** [comment]
今天用Edge和篡改猴最新的测试版又试出来了 @lisonge 

```js
if (document.head) {
	if (document.head.firstChild) {
		document.head.insertBefore(entryScript, document.head.firstChild);
	} else {
		document.head.appendChild(entryScript);
	}
} else {
	if (document.documentElement.firstChild) {
		document.documentElement.insertBefore(
			entryScript,
			document.documentElement.firstChild
		);
	} else {
		document.documentElement.appendChild(entryScript);
	}
}
```

https://github.com/lisonge/vite-plugin-monkey/assets/50544447/03c2f287-b76c-458b-971a-bea4b92d31db
