### ISSUE TITLE
将Antd写入externalGlobals后，打包的文件运行报错

### ISSUE THREAD

**Issue by laicengfan** [lisonge/vite-plugin-monkey#158]
vite配置：
![image](https://github.com/lisonge/vite-plugin-monkey/assets/27845564/594763b2-893e-4c77-8506-b5a160ff9659)

构建require：
![image](https://github.com/lisonge/vite-plugin-monkey/assets/27845564/fffaa5b9-1144-4e6b-a7de-fc26552585f1)

报错信息：
![image](https://github.com/lisonge/vite-plugin-monkey/assets/27845564/dea9f530-c4d9-49fd-a245-f5ea5d95edb1)

请问下这个报错信息是怎么回事呢

**Comment by lisonge** [comment]
add `dayjs` after `ReactDOM`

```txt
        externalGlobals: {
          react: cdn.jsdelivr('React', 'umd/react.production.min.js'),
          'react-dom': cdn
            .jsdelivr('ReactDOM', 'umd/react-dom.production.min.js')
            .concat('https://cdn.jsdelivr.net/npm/dayjs'),
        },
```

**Comment by laicengfan** [comment]
3q！
