### ISSUE TITLE
不知道什么问题导致vue for循环渲染滞后

### ISSUE THREAD

**Issue by lvzhenbo** [lisonge/vite-plugin-monkey#159]
一时半会真不知道怎么描述，先给个gif图
![动画 (0)](https://github.com/lisonge/vite-plugin-monkey/assets/32427677/a2d51854-b1bd-45b6-b614-1d0e575dc20d)

**Comment by lvzhenbo** [comment]
我测试过简单的项目没有什么问题，就我这个快写好的有问题
https://github.com/lvzhenbo/115-plus

**Comment by lvzhenbo** [comment]
我测试过简单的项目没有什么问题，就我这个快写好的有问题
https://github.com/lvzhenbo/115-plus

**Comment by lvzhenbo** [comment]
就是节点都渲染了，就是不渲染文字，然后等关闭的一瞬间文字就渲染出来了

**Comment by lvzhenbo** [comment]
![image](https://github.com/lisonge/vite-plugin-monkey/assets/32427677/bb7c8f47-c869-42ca-a5fc-7270860b070d)
![image](https://github.com/lisonge/vite-plugin-monkey/assets/32427677/7365c6f9-99e5-46ed-ad10-80983dfc8527)
我想我找到什么问题了，但是我不知道怎么解决

**Comment by lisonge** [comment]
在 `vite dev` 下是否会出现此问题

**Comment by gxr404** [comment]
和这个项目没什么关系吧。。你的getDownLoadUrl调用时直接就返回了 
```js
download = {
    name: "",
    url: "",
}
```
这个空对象 接口返回后 直接修改了download， 这种改法响应了丢失了，数据变了不渲染
```js
// 原写法
download.name = data.file_name;
download.url = data.url.url;
// 改成这样
const index = downloads.value.indexOf(download)
downloads.value[index].name = data.file_name;
downloads.value[index].url = data.url.url;
```

**Comment by lvzhenbo** [comment]
好吧，打扰了，确实是我的问题，习惯axios这种封装好的异步以后，同步都不知道怎么写了
