### ISSUE TITLE
打包后monkeyWindow上的key构造异常

### ISSUE THREAD

**Issue by rachpt** [lisonge/vite-plugin-monkey#163]
提示：
```
userscript.html?name=mt-work-enhancement.user.js&id=20b35579-0c2f-4001-ae64-150e7bb31f60:741  Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at Object.execute (userscript.html?name=mt-work-enhancement.user.js&id=20b35579-0c2f-4001-ae64-150e7bb31f60:741:35)
    at r (userscript.html?name=mt-work-enhancement.user.js&id=20b35579-0c2f-4001-ae64-150e7bb31f60:44:3638)
    at v (userscript.html?name=mt-work-enhancement.user.js&id=20b35579-0c2f-4001-ae64-150e7bb31f60:44:4074)
    at userscript.html?name=mt-work-enhancement.user.js&id=20b35579-0c2f-4001-ae64-150e7bb31f60:44:3551
```
module.meta::: 值为 {url: './__entry.js', resolve: ƒ}

打包后异常位置：
<img width="1026" alt="image" src="https://github.com/lisonge/vite-plugin-monkey/assets/25758867/75ae62eb-3408-4c10-b602-b7d09f303415">

对应plugin代码位置：
<img width="959" alt="image" src="https://github.com/lisonge/vite-plugin-monkey/assets/25758867/6f968458-dc5b-4499-8c46-88c87999f754">

dev模式正常，build后异常，手动将打包后的 `module.meta.url` 位置改成 `module.meta.url?.startsWith('http') ? module.meta.url : location.href` 后正常。
咨询一下优雅一点的解决办法。

**Comment by lisonge** [comment]
<https://github.com/lisonge/vite-plugin-monkey?tab=readme-ov-file#how-to-properly-build-a-library-using-gm_api>

```txt
    esbuildOptions: (options) => {
      options.alias = {
        'vite-plugin-monkey/dist/client': 'vite-plugin-monkey/dist/native',
      };
    },
```

**Comment by lisonge** [comment]
https://github.com/lisonge/vite-plugin-monkey/releases/tag/v4.0.1

**Comment by rachpt** [comment]
感谢回复&修复，刚刚本地该vite-plugin-monkey 的代码一直没有相关。 排查了一圈是 [@sec-ant/gm-fetch](https://github.com/Sec-ant/gm-fetch) 这个包引入的 vite-plugin-monkey 旧版本的代码，还的他那边更新才能彻底解决。
 
<img width="1109" alt="image" src="https://github.com/lisonge/vite-plugin-monkey/assets/25758867/5d14bda7-defb-4a15-9743-0e80b29059dd">
