### ISSUE TITLE
GM.xmlHttpRequest not resolvable without reconfiguring minify

### ISSUE THREAD

**Issue by blakehurd** [lisonge/vite-plugin-monkey#166]
Thanks for the plugin, it remains useful!

The default minify ON settings appear to clobber the following:

```
import {
    GM,
} from '$';

const STREAMING_SUPPORTED = GM.xmlHttpRequest?.RESPONSE_TYPE_STREAM;
console.log('Streaming supported: ', STREAMING_SUPPORTED);

.... using GM.xmlHttpRequest in code instead of GM_xmlHttpRequest, to maintain compatibility with Greasemonkey/GM API 4 while supporting Tampermonkey and others.
```

Is this intentional? By clobber, I mean these references resolve to "undefined" in Greasemonkey and Tampermonkey, instead of resolving to 'stream' and the appropriate xhr function.

When I add this configuration to Vite, then it works:
`  esbuild: {
    minifyIdentifiers: false,
    keepNames: true,
  },`

But it doesn't minify as completely as it could. Ideally this would work with default minify.

**Comment by lisonge** [comment]
what is your raw code, build config and product code

**Comment by blakehurd** [comment]
So the code in question is https://greasyfork.org/en/scripts/472236-gm-fetch/code but lightly revised to work with GM.xmlHttpRequest only instead of GM_xmlhttprequest, which ensures it works on Greasemonkey too (besides Tampermonkey).

build config
```
xport default defineConfig({
  plugins: [
    monkey({
      entry: 'src/main.js',
      userscript: {
        author: 'foo',
        description: 'foo',
        name: 'foo',
        namespace: 'bar',
        downloadURL:
          '...',
        updateURL:
          '...',
        match: [
            // ...
        ],
      },
      build: {
        fileName: 'foo.user.js',
        metaFileName: true,
      },
    }),
  ],
  build: {
    minify: true,
  },
  // TODO: https://github.com/lisonge/vite-plugin-monkey/issues/166 default minify settings appear to clobber GM.xmlHttpRequest. Reconfiguring esbuild's minify settings mitigates this, at the cost of a slightly less minified userscript. (+43 kB)
  esbuild: {
    minifyIdentifiers: false,
    keepNames: true,
  },
});
```

If you want a full printout let me know. Not sure what else you need?

**Comment by lisonge** [comment]
Can you provide the repository url to reproduce this issue?

Or you can upload a repository zip file to the github comment section

**Comment by blakehurd** [comment]
[output.zip](https://github.com/user-attachments/files/15812420/output.zip)
[jstest.user.js.txt](https://github.com/user-attachments/files/15812430/jstest.user.js.txt)

Please let me know if any issues reproducing the issue. Attached a sample user.js with the default minify settings.

**Comment by lisonge** [comment]
This is caused by `autoGrant`, you can manually set `grant` to solve it

```txt
grant: ['GM.xmlHttpRequest'],
```

**Comment by Sec-ant** [comment]
@blakehurd Hi, I'm the maintainer of the said script ([`gm-fetch`](https://github.com/Sec-ant/gm-fetch)) you'd like to adapt. Just want you to know I'd love to accept PRs for it to be compatible with Greasemonkey in a non-breaking way, but of course it's entirely up to you :)
