### ISSUE TITLE
In tampermonkey, disable <script> on dev, disable server:<script> on preview? (only 1 script active at any time)

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [lisonge/vite-plugin-monkey#167]
Is there any way to not have to disable the built script when going back to dev? I end up with both the server script and the client script running at the same time so the script runs twice.

**Comment by lisonge** [comment]
what is `server script` and `client script` ?

**Comment by henrikvilhelmberglund** [comment]
> what is `server script` and `client script` ?

Sorry for the poor explanation, server script is the result of `npm run dev`, client script is the result of `npm run build` and `npm run preview`.

So: (in tampermonkey dashboard) 
`npm run dev` -> `server<script>`
`npm run dev` and `npm run preview` -> `<script>`

After dev and build&preview I end up with two scripts which is fine when the development server is offline, however when I want to edit the script again I have two active scripts. I would like to know if there is a way to automatically disable the built client script when running `npm run dev` and also disable the development server script when running `npm run preview`.

**Comment by lisonge** [comment]
set [server.prefix](https://github.com/lisonge/vite-plugin-monkey/blob/1efe9fb27aedbac48e7686b8210d634889c8f1b0/packages/vite-plugin-monkey/src/node/types.ts#L159) to `false`

**Comment by henrikvilhelmberglund** [comment]
> set [server.prefix](https://github.com/lisonge/vite-plugin-monkey/blob/1efe9fb27aedbac48e7686b8210d634889c8f1b0/packages/vite-plugin-monkey/src/node/types.ts#L159) to `false`

😨 Thanks!
