### ISSUE TITLE
externalResource 排除路径中包含@开头编译报错

### ISSUE THREAD

**Issue by shu810687117** [lisonge/vite-plugin-monkey#169]
使用排除的css的CND
`externalResource:{
'@layui/layui-vue/lib/index.css':cdn.jsdelivr()
}`

编译提示的错误：

`Could not load monkey-resource-import:@layui/layui-vue/lib/index.css (imported by src/main.js): Package subpath './lib/index.css' is not defined by "exports" in E:\ide_project\lib\node_modules\@layui\layui-vue\package.json imported from E:\ide_project\lib\any.js`

**Comment by lisonge** [comment]
https://github.com/lisonge/vite-plugin-monkey/releases/tag/v4.0.5
