### ISSUE TITLE
staticfile已遭到攻击被人控制！！！！！！！！！！！！！！

### ISSUE THREAD

**Issue by lvzhenbo** [lisonge/vite-plugin-monkey#171]
相关新闻
https://www.bleepingcomputer.com/news/security/polyfillio-bootcdn-bootcss-staticfile-attack-traced-to-1-operator/
https://v2ex.com/t/1053497
https://github.com/staticfile/static/issues/700
uBlockOrigin已开启屏蔽
https://github.com/uBlockOrigin/uAssets/blob/18d04c52e9a7d2165b3164766bb2db17d10e78b5/filters/badware.txt#L4169
greasyfork也把域名拉入黑名单
![image](https://github.com/lisonge/vite-plugin-monkey/assets/32427677/2df34c9b-de7d-4407-bdb8-54d672fd937b)

**Comment by lisonge** [comment]
https://github.com/lisonge/vite-plugin-monkey/releases/tag/v4.0.4
