### ISSUE TITLE
This request has been blocked; the content must be served over HTTPS

### ISSUE THREAD

**Issue by laboratorys** [lisonge/vite-plugin-monkey#179]
Chrome 129.0.6637.0

Mixed Content: The page at 'https://www.google.com/' was loaded over HTTPS, but requested an insecure script 'http://localhost:8991/__vite-plugin-monkey.entry.js'. This request has been blocked; the content must be served over HTTPS

尝试了禁用CSP，无效

![Clip_2024-08-15_18-11-35](https://github.com/user-attachments/assets/a7298036-97f7-4661-bb7d-acaca8803df0)

**Comment by lisonge** [comment]
这不是 csp ，这是 https 网页里不能使用 http 资源 的报错

将 localhost 换成 127.0.0.1 应该可解决

另外为什么你的资源地址默认不是 127.0.0.1

**Comment by laboratorys** [comment]
> 这不是 csp ，这是 https 网页里不能使用 http 资源 的报错
> 
> 将 localhost 换成 127.0.0.1 应该可解决
> 
> 另外为什么你的资源地址默认不是 127.0.0.1
已解决，我把host改成了0.0.0.0
