### ISSUE TITLE
@tag support / 关于@tag 元信息支持

### ISSUE THREAD

**Issue by qwertycxz** [lisonge/vite-plugin-monkey#181]
[@tag](https://www.tampermonkey.net/documentation.php#meta:tag) seems not working.
There should be a `tag` key in the [`TampermonkeyUserScript`](https://github.com/lisonge/vite-plugin-monkey/blob/main/packages/vite-plugin-monkey/src/node/userscript/tampermonkey.ts#L81)

[@tag](https://www.tampermonkey.net/documentation.php#meta:tag)不可用。
大概在[`TampermonkeyUserScript`](https://github.com/lisonge/vite-plugin-monkey/blob/main/packages/vite-plugin-monkey/src/node/userscript/tampermonkey.ts#L81)这里加一个`tag`键就好。

**Comment by lisonge** [comment]
```txt
        userscript: {
          $extra:[
            ['tag',[ 'your_custom_tag', 'your_custom_value']]
          ]
        },
```

**Comment by lisonge** [comment]
https://github.com/lisonge/vite-plugin-monkey/releases
