### ISSUE TITLE
require 引入 jquery 依赖失败 

### ISSUE THREAD

**Issue by dlzmoe** [lisonge/vite-plugin-monkey#183]
unpkg 和 jsdelivr 都尝试过，最后打包的 `user.js` 不存在 require jquery，dev 倒是正常的，可以测试下

```js
externalGlobals: {
    vue: cdn.unpkg('Vue', 'dist/vue.global.prod.js'),
    jquery: cdn.unpkg("jQuery", "dist/jquery.js")
    // or
    // jquery: cdn.unpkg("jQuery")
},
```

**Comment by lisonge** [comment]
vite 不支持 `require` 请使用 `import`

**Comment by lisonge** [comment]
> 最后打包的 user.js 不存在 require jquery

需要给出复现 demo

**Comment by dlzmoe** [comment]
https://github.com/dlzmoe/demo-vite-plugin-monkey

上传了demo，录制了一个演示视频

https://github.com/user-attachments/assets/28b3bfcb-762d-4522-b7d2-d96c7e51c714

**Comment by lisonge** [comment]
你没有在代码里使用 `jquery` 所以打包出来的没有 `@require jquery <url>`
