### ISSUE TITLE
dev模式下，代码会执行2次

### ISSUE THREAD

**Issue by xiaohail** [lisonge/vite-plugin-monkey#185]
在chrome sources标签中，
会看到一个main.tsx源码文件 和一个main.tsx编译后的文件，

我的部分业务无实际页面，只有纯js useEffect会被执行2次
<img width="206" alt="image" src="https://github.com/user-attachments/assets/25d8ec09-bce7-42ef-97b2-12484a8e514a">

**Comment by lisonge** [comment]
https://react.dev/reference/react/StrictMode
