### ISSUE TITLE
cdn配置问题

### ISSUE THREAD

**Issue by XianRuiMa** [lisonge/vite-plugin-monkey#187]
作者大大，以下几种情况，能配置cdn不
1. https://cdn.jsdelivr.net/npm/magic-bytes.js@1.10.0/dist/index.min.js
2. https://cdn.jsdelivr.net/npm/dayjs@1.11.13/plugin/utc.js
3. https://cdn.jsdelivr.net/npm/google-timezones-json@1.2.0/index.min.js

**Comment by lisonge** [comment]
1. no
2. `dayjs_plugin_utc`
3. no

**Comment by lisonge** [comment]
just check if it includes `iife` or `umd` format js file

**Comment by XianRuiMa** [comment]
第二个该如何配置cnd呢
以下代码用于时间格式化为指定时区的时间
```js
import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';
import timezone from 'dayjs/plugin/timezone'; // dependent on utc plugin
dayjs.extend(utc);
dayjs.extend(timezone);
console.log(dayjs(1726914273000).tz( 'Asia/Shanghai' ).format('YYYY年MM月DD日HH时mm分ss秒')
```
