### ISSUE TITLE
GM_info类型扩充

### ISSUE THREAD

**Issue by lvzhenbo** [lisonge/vite-plugin-monkey#190]
详见：https://www.tampermonkey.net/documentation.php?ext=dhdg&version=5.3.2#api:GM_info

**Comment by lisonge** [comment]
https://github.com/lisonge/vite-plugin-monkey/tree/dev

目前正在重构类型支持，会逐渐完善

**Comment by lisonge** [comment]
https://github.com/lisonge/vite-plugin-monkey/releases
