### ISSUE TITLE
Api GM.getResourceUrl

### ISSUE THREAD

**Issue by WhiteSevs** [lisonge/vite-plugin-monkey#192]
https://www.tampermonkey.net/documentation.php?ext=dhdg&version=5.3.2#api:GM_getResourceURL

之前官方文档的是`GM.getResourceURL`，而实际的Api是`GM.getResourceUrl`，反馈后修复了这个问题，`vite-plugin-monkey`需要修复这个问题

**Comment by WhiteSevs** [comment]
https://github.com/lisonge/vite-plugin-monkey/blob/e99638797aa8a7fbbbaacde3c7e532cc2ebe066a/packages/vite-plugin-monkey/src/client/types/gm.ts#L56

**Comment by WhiteSevs** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/2249

**Comment by lisonge** [comment]
https://github.com/lisonge/vite-plugin-monkey/releases
