### ISSUE TITLE
在调试时如何临时禁止热更

### ISSUE THREAD

**Issue by yangfeng20** [lisonge/vite-plugin-monkey#195]
我的场景是在开发环境调试，但是一小点的代码改动，就会引起热更，导致页面被重新加载。

我希望的是代码临时停止热更，我修改完成之后统一热更，但同时这期间，代码还在运行。

**Comment by yangfeng20** [comment]
有临时的方案也可以。

**Comment by lisonge** [comment]
和正常开发 vite 项目一样

https://stackoverflow.com/questions/72548801
