### ISSUE TITLE
(await import("json-to-ts")).default 打包报错

### ISSUE THREAD

**Issue by wencaizhang** [lisonge/vite-plugin-monkey#199]
开发环境正常运行，但是打包会报错
<img width="830" alt="image" src="https://github.com/user-attachments/assets/e18d6875-7505-4b08-b17b-6820b43d004e">

我把 `(await import("json-to-ts")).default` 部分代码注释掉，就能打包成功了。

我找到了官方提供的示例：[https://github.com/lisonge/vite-plugin-monkey/blob/main/playground/dynamic-import/src/main.ts](https://github.com/lisonge/vite-plugin-monkey/blob/main/playground/dynamic-import/src/main.ts)
但是其中的 md5 文件是通过 `externalGlobals` 引入的，而我这里是通过 pnpm 安装的，略有不同。

```ts
       externalGlobals: {
          md5: cdn.jsdelivr('MD5', 'dist/md5.min.js'),
       },
```

请问我该怎么写呢？

**Comment by lisonge** [comment]
```ts
import jsonTots from 'json-to-ts'
```

**Comment by wencaizhang** [comment]
> ```ts
> import jsonTots from 'json-to-ts'
> ```

成了，竟然可以直接引入 cjs 啊，我还在各种找方案 😂
