### ISSUE TITLE
externalResource 貌似不能正确支持 ?raw

### ISSUE THREAD

**Issue by Tsuk1ko** [lisonge/vite-plugin-monkey#20]
我看到 externalResource 里面有处理 `?raw`

https://github.com/lisonge/vite-plugin-monkey/blob/418ffb85dca2eb91260b3bc22bab110c7202bff7/packages/vite-plugin-monkey/src/node/plugins/externalResource.ts#L86-L93

因此我猜想我应该是可以这样使用的

```js
import { GM_addStyle } from '$';
import elementPlusCss from 'element-plus/dist/index.css?raw';
// 自行在某个需要的时候才动态引入
GM_addStyle(elementPlusCss);
```

```js
// in monkey config
externalResource: {
  'element-plus/dist/index.css?raw': cdn.jsdelivrFastly(undefined, 'dist/index.css'),
}
```

但实际上不管用，经过测试我发现，问题出在这里

https://github.com/lisonge/vite-plugin-monkey/blob/418ffb85dca2eb91260b3bc22bab110c7202bff7/packages/vite-plugin-monkey/src/node/plugins/externalResource.ts#L48-L53

不知道为什么此处 id 实际为 `element-plus/dist/index.css?used&raw`，多了个 `used&`，导致没有匹配上 externalResource

将 externalResource 配置里的 key 改为 `element-plus/dist/index.css?used&raw` 就可以顺利走进 load 钩子了，不过因为结尾并不是 `?raw` 因此没有匹配上 raw 的处理，还是会有问题

**Comment by lisonge** [comment]
这个我之前遇到过，后来写着写着就忘记了怎么触发这个used，

我明天修复一下吧，你可以先用自定义loader处理

**Comment by lisonge** [comment]
对了，为了兼容 cdn.xxx 这类函数的类型，长度为 0 的字符串被认为是 undefined 转而使用缺省值，优点是大多数情况下只需要使用 cdn.xxx() 无需传递两个参数，externalResource 配置是能自动推断 pathname 的

**Comment by lisonge** [comment]
fixed by [v2.4.2](https://github.com/lisonge/vite-plugin-monkey/blob/v2.4.2/packages/vite-plugin-monkey/CHANGELOG.md)
