### ISSUE TITLE
Support GM_registerMenuCommand for 3 arguments

### ISSUE THREAD

**Issue by WhiteSevs** [lisonge/vite-plugin-monkey#203]
![PixPin_2024-12-20_23-04-54](https://github.com/user-attachments/assets/e262eae0-60a8-4ae1-ac3a-005f3a9cfbe7)

![PixPin_2024-12-20_23-08-49](https://github.com/user-attachments/assets/75edc259-c5e0-4121-9158-d1efa96176ae)

**Comment by lisonge** [comment]
https://github.com/lisonge/vite-plugin-monkey/releases/tag/v5.0.1
