### ISSUE TITLE
CORS and TrustedScriptURL error on chrome

### ISSUE THREAD

**Issue by festoney8** [lisonge/vite-plugin-monkey#205]
### 1. CORS
Dev mode script on **Chrome>=130** sometimes blocked by CORS now. All PNA restrictions were enforced tentatively in Chrome 130 according to [blog 1](https://developer.chrome.com/blog/pna-on-hold) and [blog 2](https://developer.chrome.com/blog/private-network-access-update-2024-03). (I haven't found any doc related to this feature of the Edge browser)

I found a similar issue #146, can this be solved by official support instead of writing developers' own vite plugin?

![image](https://github.com/user-attachments/assets/5cae04c0-2384-41e3-bdac-c7244afce1c7)

### 2. TrustedScriptURL
It's weird that when using a wildcard in domain matching, such as `match: ["https://*.google.com/*"]`, chrome  will report the following TrustedScriptURL error, but `match: ["https://www.google.com/*"]` works fine

![image](https://github.com/user-attachments/assets/bb306cc0-3fc8-455d-a061-01b973e0836e)

### Minimum reproduce

My env: win10 + chrome131 + tampermonkey

File: [monkey-demo.zip](https://github.com/user-attachments/files/18264676/monkey-demo.zip)

Run dev mode, visit https://www.baidu.com/ can get CORS error, visit https://www.google.com/ can get TrustedScriptURL error

**Comment by lisonge** [comment]
> can this be solved by official support instead of writing developers' own vite plugin?

https://github.com/lisonge/vite-plugin-monkey/commit/a068f38b12988d48bd92ecee15bfebe0057705d7

---

>  such as match: ["https://*.google.com/*"], chrome will report the following TrustedScriptURL error

I can't reproduce it in tampermonkey5.3.3/chrome131.0.6778.205

![image](https://github.com/user-attachments/assets/7b629c10-9902-472d-b232-b17c460b4b97)

**Comment by lisonge** [comment]
you can test the following code by replace the bottom position code of this file
![image](https://github.com/user-attachments/assets/7c78fdde-8ba1-402c-9df0-d9883e59b0bb)


```js
;(({ entrySrc }) => {
  window.GM;
  const key = `__monkeyWindow-` + new URL(entrySrc).origin;
  document[key] = window;
  console.log(`[vite-plugin-monkey] mount monkeyWindow to document`);
  if (typeof GM_addElement === "function") {
    GM_addElement(document.head, "script", {
      type: "module",
      src: entrySrc
    });
  } else {
    const script = document.createElement("script");
    script.type = "module";
    if (globalThis.trustedTypes) {
      const policy = globalThis.trustedTypes.createPolicy(key, {
        createScriptURL: (input) => input
      });
      const trustedScriptURL = policy.createScriptURL(entrySrc);
      script.src = trustedScriptURL;
    } else {
      script.src = entrySrc;
    }
    document.head.append(script);
  }
  console.log(`[vite-plugin-monkey] mount entry module to document.head`);
})(...[
  {
    "entrySrc": "http://127.0.0.1:5173/__vite-plugin-monkey.entry.js"
  }
]);
```

**Comment by festoney8** [comment]
It works! Now the TrustedScriptURL error is gone. Only a few CSP errors left, which can be solved by Disable-CSP extension

![image](https://github.com/user-attachments/assets/e132d8b0-3d4f-4673-9019-67220682e0cc)

**Comment by lisonge** [comment]
https://github.com/lisonge/vite-plugin-monkey/releases/tag/v5.0.4
