### ISSUE TITLE
externalResource 中 raw / url 导入的处理问题

### ISSUE THREAD

**Issue by Tsuk1ko** [lisonge/vite-plugin-monkey#21]
https://github.com/lisonge/vite-plugin-monkey/blob/b4366118abf404ffb772e67ca9444809066ecd6c/packages/vite-plugin-monkey/src/node/plugins/externalResource.ts#L130-L165

此处的 else if 在扩展名判断处断开了，导致扩展名处理会覆盖 raw / url 的处理，按理来说应该全部用 else if 连接

**Comment by lisonge** [comment]
fixed by [v2.4.4](https://github.com/lisonge/vite-plugin-monkey/blob/v2.4.4/packages/vite-plugin-monkey/CHANGELOG.md)
