### ISSUE TITLE
react-ts 模板提示一堆错误

### ISSUE THREAD

**Issue by lgf-136** [lisonge/vite-plugin-monkey#23]
pnpm create monkey 然后选react-ts 模板提示一堆错误。

![image](https://user-images.githubusercontent.com/86616706/192704864-715fbe78-5193-42dd-a878-f3c211beec93.png)

**Comment by lisonge** [comment]
fixed by [2.5.1](https://github.com/lisonge/vite-plugin-monkey/blob/v2.5.1/packages/vite-plugin-monkey/CHANGELOG.md)

**Comment by lisonge** [comment]
将你的项目里的 `package.json` 的 `"vite-plugin-monkey": "^2.5.0"` 改成 `"vite-plugin-monkey": "^2.5.1"` 即可
