### ISSUE TITLE
使用@douyinfe/semi-ui cdn打包 error  Unexpected "@"

### ISSUE THREAD

**Issue by yelc66** [lisonge/vite-plugin-monkey#24]
麻烦您帮忙看一下，是我导入cdn设置不对嘛，导入组件是按需引用的，
![Snipaste_2022-09-30_09-23-00](https://user-images.githubusercontent.com/48628500/193169887-945d4776-c8f8-4a25-9346-edcec107d73c.png)
![Snipaste_2022-09-30_09-21-43](https://user-images.githubusercontent.com/48628500/193169894-13a6c618-1fc7-4823-b8f1-2332a9c199d1.png)
![Snipaste_2022-09-30_09-17-19](https://user-images.githubusercontent.com/48628500/193169899-e32ca55f-45aa-4afe-8a71-938be4eb7b34.png)

**Comment by lisonge** [comment]
cdn.xxx 的第1个参数应该是一个 JavaScript 表达式，显然 `@DouYinFeSemiIcons` 不是

**Comment by lisonge** [comment]
`@douyinfe/semi-ui` 的导出名字是 `SemiUI`
![image](https://user-images.githubusercontent.com/38517192/193170502-c15901cf-a433-4159-bf79-e804d811798d.png)

`@douyinfe/semi-icons` 的导出名字是 `SemiIcons`
![image](https://user-images.githubusercontent.com/38517192/193170671-93e55e11-aeef-4292-bd03-80acd30d1f6d.png)

很多库往往都不注明自己的 iife/umd 的导出变量名字，需要自己到 js 文件里去找

**Comment by lisonge** [comment]
另外你的脚本的 `namespace` 建议设置为你的github地址 `https://github.com/yelc66`

**Comment by yelc66** [comment]
> 另外你的脚本的 `namespace` 建议设置为你的github地址 `https://github.com/yelc66`

好的，已修改，谢谢
