### ISSUE TITLE
使用vue的js模板构建的项目，无法使用pnpm run dev 预览脚本。I can't preview the script.

### ISSUE THREAD

**Issue by Discut** [lisonge/vite-plugin-monkey#26]
## 我的环境 My context
+ edge
+ js+vue
+ ![image](https://user-images.githubusercontent.com/71692038/194712661-4565fd6b-5467-44d5-a01e-7110c5cbbf28.png)

## 发生的问题 Problems that occur
使用命令「pnpm run dev」预览脚本，添加脚本后打开匹配网站，在控制台出现如下错误
Use the command "pnpm run dev" to preview the project, an error occurred at the console, the project preview failed.
![image](https://user-images.githubusercontent.com/71692038/194712985-bc08bc1c-c461-463e-af40-a080f3bd216b.png)
client.ts:470:16 in 
![image](https://user-images.githubusercontent.com/71692038/194713023-e4f4c1cc-b959-4572-87c7-09543e269864.png)
style.css:1:96 in
![image](https://user-images.githubusercontent.com/71692038/194713066-35e01f6e-3c0b-43c4-a9f8-031ff9ffb7f2.png)

## 如何复现 Reproduction of the problem
修改vite.config.js 中的
Modify the file "vite.config.js "
![image](https://user-images.githubusercontent.com/71692038/194713197-97a659a7-7e40-4619-a8c6-3498aee4f923.png)

## 更多 More
当我直接构建项目然后导入至油猴插件时，脚本就能正常运行了。
我尝试过直接使用模板在该网站预览，还是会发生同样的错误。
使用该项目在其他网站预览（例如哔哩哔哩），就不会发生这种问题。

When I build the project directly and import it into the Monkey, the script works fine.
I preview the template project on the website and the same error still occurs.
If i preview the project on other websites ( For example, bilibili ), the error does not occur.

以上就是我的问题了，感谢大佬抽空查看我的问题，如果有解决方案就更好了。（一个前端小白）也许我可能遗留了某些配置文件吧，求大佬轻喷。

**Comment by lisonge** [comment]
请问你创建的项目的仓库地址是什么，可否发出来看看

**Comment by Discut** [comment]
> 请问你创建的项目的仓库地址是什么，可否发出来看看

这是项目地址
https://github.com/Discut/ID_School
我并没有修改太多，使用pnpm create monkey 创建的模板项目在那个网站下预览也会爆同样的错误。

**Comment by lisonge** [comment]
找到原因了，是 `https://mooc.yibinu.edu.cn/js/core.min.js` 这个太旧了，覆盖了你的浏览器的 api，导致 Map 这个对象缺失属性

解决方法之一是 在 devtools 阻止这个 url
![image](https://user-images.githubusercontent.com/38517192/194715083-8d9959fc-2a3f-4185-998e-f4b10a22735a.png)
![image](https://user-images.githubusercontent.com/38517192/194715135-a4d43ec7-a5fb-4065-8f7a-d5b7d32b2862.png)

**Comment by Discut** [comment]
> 找到原因了，是 `https://mooc.yibinu.edu.cn/js/core.min.js` 这个太旧了，覆盖了你的浏览器的 api，导致 Map 这个对象缺失属性
> 
> 解决方法之一是 在 devtools 阻止这个 url ![image](https://user-images.githubusercontent.com/38517192/194715083-8d9959fc-2a3f-4185-998e-f4b10a22735a.png) ![image](https://user-images.githubusercontent.com/38517192/194715135-a4d43ec7-a5fb-4065-8f7a-d5b7d32b2862.png)

感谢大佬解决我的问题。

**Comment by lisonge** [comment]
另一种解决方法是 直接覆盖它的 polyfill
![image](https://user-images.githubusercontent.com/38517192/194715383-344108e2-acb7-4193-bf40-9707e1fb3f4f.png)
