### ISSUE TITLE
支持多国语系配置 name, description

### ISSUE THREAD

**Issue by pionxzh** [lisonge/vite-plugin-monkey#28]
根据 https://greasyfork.org/zh-CN/help/meta-keys#meta-name-localized

希望可以提供某种方式来配置这种语言相关的meta

>@name:XX-YY
>脚本在特定语言区域的标题。XX 指 [ISO 639-1 国家代码](http://www.loc.gov/standards/iso639-2/php/code_list.php) 以及 YY 指可选的 [ISO 3166 地区代码](https://www.iso.org/obp/ui/#search)。该选项用于提供多语言的@name 脚本名称。
@description:XX-YY
>用某门语言写成的脚本描述。XX 指 [ISO 639-1 国家代码](http://www.loc.gov/standards/iso639-2/php/code_list.php) 以及 YY 指可选的 [ISO 3166 地区代码](https://www.iso.org/obp/ui/#search)。该选项用于提供多语言的@description 脚本介绍。

**Comment by lisonge** [comment]
有没有可能本来就支持

<https://github.com/lisonge/vite-plugin-monkey/blob/68ead3a81dd333f975504b919de3defb75cd26b1/playground/example/vite.config.ts#L8-L23>

**Comment by pionxzh** [comment]
我的眼睛 😂
