### ISSUE TITLE
怎么获取 MonkeyOption 这个 type

### ISSUE THREAD

**Issue by ilyydy** [lisonge/vite-plugin-monkey#30]
看代码没有 export，不能直接 import 这个类型

这样倒是可以，但感觉不太好
```ts
import type { MonkeyOption } from 'vite-plugin-monkey/src/node/types';
```

**Comment by lisonge** [comment]
```ts
import monkey from 'vite-plugin-monkey';
type MonkeyOption = Parameters<typeof monkey>[0]
```
<https://www.typescriptlang.org/docs/handbook/utility-types.html#parameterstype>

**Comment by lisonge** [comment]
后续版本会支持直接导出 `MonkeyOption`

**Comment by lisonge** [comment]
[v2.8.0](https://github.com/lisonge/vite-plugin-monkey/blob/v2.8.0/packages/vite-plugin-monkey/CHANGELOG.md) 已支持

```ts
import type { MonkeyOption } from 'vite-plugin-monkey';
```
