### ISSUE TITLE
Uncaught ReferenceError: __MONKEY_WINDOW__ is not defined

### ISSUE THREAD

**Issue by jianzhichun** [lisonge/vite-plugin-monkey#32]
Uncaught ReferenceError: __MONKEY_WINDOW__ is not defined

**Comment by lisonge** [comment]
可否给出报错截图，你这个错误应该来自 <https://unpkg.com/browse/vite-plugin-monkey@2.9.0/dist/client/index.mjs>，貌似是路径分隔符的问题

**Comment by lisonge** [comment]
如果你想手动修复它，可以手动配置 `define`

```ts
// vite.config.ts
import { defineConfig } from 'vite';
import monkey from 'vite-plugin-monkey';

export default defineConfig(({ command }) => {
  return {
    define: {
      __MONKEY_WINDOW__:
        command == 'serve' ? `document.__monkeyWindow` : `window`,
    },
    plugins: [
      monkey({
        entry: 'src/main.ts',
        userscript: {
          icon: 'https://vitejs.dev/logo.svg',
          namespace: 'npm/vite-plugin-monkey',
          match: ['https://i.songe.li/*'],
          connect: [`httpbin.org`, `i.pximg.net`],
        },
      }),
    ],
  };
});
```

**Comment by lisonge** [comment]
可以试试安装 [v2.9.1](https://github.com/lisonge/vite-plugin-monkey/blob/v2.9.1/packages/vite-plugin-monkey/CHANGELOG.md)

**Comment by lisonge** [comment]
是插件没有作用到 vite 的预构建，我修复一下即可

**Comment by lisonge** [comment]
fixed by  [v2.9.2](https://github.com/lisonge/vite-plugin-monkey/blob/v2.9.2/packages/vite-plugin-monkey/CHANGELOG.md)

```shell
pnpm add vite-plugin-monkey@2.9.2
```

**Comment by lisonge** [comment]
使用 `define` 后发现了 `以前未发现的问题`

`v2.9.2` 的注入模式使得 `/@vite/client` 和 `/src/main.ts` 并行下载，无法保证正确的执行顺序

该问题已在 [v2.9.3](https://github.com/lisonge/vite-plugin-monkey/blob/v2.9.3/packages/vite-plugin-monkey/CHANGELOG.md) 解决

```shell
pnpm add vite-plugin-monkey@2.9.3
```
