### ISSUE TITLE
关于使用 vite-plugin-monkey脚手架搭建的react项目无法使用GM_SETVALUE的问题

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [lisonge/vite-plugin-monkey#35]
node版本：v16.18.0   npm v8.19.2
![image](https://user-images.githubusercontent.com/59086082/206194175-34da39f9-2cb4-446c-946b-4af2916bc16f.png)
![image](https://user-images.githubusercontent.com/59086082/206194540-f9bf5c44-6b33-4b5a-bbd3-e213b3cf25da.png)

不太懂引入的正确方式，希望可以指点一下

**Comment by lisonge** [comment]
> 然后看下之前的issue说过这样配置有效(不知道下面的方法是否还是可行的)

你写的这个配置 不能解决 你遇到的这个问题

---

你的 react 代码是运行在 unsafeWindow 作用域下，这个作用域没有 GM_api ，因此会报未定义错误
这个问题有两种解决方法，我个人推荐第一种
1. 在你的代码里头部加上 `import {GM_xxx} from 'vite-plugin-monkey/dist/client';` ，由于 `vite-plugin-monkey/dist/client` 名字太长，我给它设置了一个默认的别名 `$` ，所以用 `import {GM_xxx} from '$';` 就行
2. 设置 [MonkeyOption.server.mountGmApi](https://github.com/lisonge/vite-plugin-monkey/blob/eace20f3bb53e1358b4b04c6745be731a11757b4/packages/vite-plugin-monkey/src/node/types.ts#L190) 为 true ，它的原理就是告诉 桥接脚本，把所有的 GM_api 全部挂载到 unsafeWindow
