### ISSUE TITLE
导入vue时的相对参考路径问题

### ISSUE THREAD

**Issue by Sokwva** [lisonge/vite-plugin-monkey#36]
前提：只修改了vite.config.js中的match。
控制台：
Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".

**Comment by lisonge** [comment]
可否上传错误示例代码到 github

**Comment by Sokwva** [comment]
> 可否上传错误示例代码到 github

我是刚刚才使用npm create创建的项目，其中只修改了vite.config.js，其他的地方都没有进行过修改。

**Comment by lisonge** [comment]
> > 可否上传错误示例代码到 github
> 
> 我是刚刚才使用npm create创建的项目，其中只修改了vite.config.js，其他的地方都没有进行过修改。

请问使用的是 <https://github.com/lisonge/vite-plugin-monkey/tree/main/packages/create-monkey> 内的哪个模板？

**Comment by Sokwva** [comment]
> > > 可否上传错误示例代码到 github
> > 
> > 
> > 我是刚刚才使用npm create创建的项目，其中只修改了vite.config.js，其他的地方都没有进行过修改。
> 
> 请问使用的是 https://github.com/lisonge/vite-plugin-monkey/tree/main/packages/create-monkey 内的哪个模板？

vue ts

**Comment by lisonge** [comment]
请问修改后的 `vite.config.ts` 内容是什么？

**Comment by Sokwva** [comment]
> 

仅将14行修改为match: ["https://www.baidu.com"],其他地方没有进行修改

**Comment by Sokwva** [comment]
> 请问修改后的 `vite.config.ts` 内容是什么？

执行npm create monkey之后，修改vite.config.js的内容，将match的google改为baidu，然后执行npm run dev，之后弹出浏览器的窗口，安装完此编译的脚本之后去baidu刷新，在控制台发现的错误。

**Comment by lisonge** [comment]
请问你使用的脚本管理器是哪个？

**Comment by Sokwva** [comment]
> 请问你使用的脚本管理器是哪个？

使用的 Tampermonkey 4.16.1，从Edge浏览器的加载项商店安装，操作系统是Windows 10，Edge：108.0.1462.54。

**Comment by lisonge** [comment]
我使用 `violentmonkey`，但是 `// @match      https://www.baidu.com` 并不匹配我打开的任何一个标签

我需要至少更改成 `// @match      https://www.baidu.com/` 才会匹配

**Comment by Sokwva** [comment]
> 



> 我使用 `violentmonkey`，但是 `// @match https://www.baidu.com` 并不匹配我打开的任何一个标签
> 
> 我需要至少更改成 `// @match https://www.baidu.com/` 才会匹配

我刚刚直接打开油猴脚本管理器，打开此脚本的编辑器，在其中第一行之前加入了一条打印信息，发现其就算没有在结尾加"/"，也能执行。我稍后换为violentmonkey测试一下。

**Comment by lisonge** [comment]
当我使用 `tampermonkey` 时，我打开 <https://www.baidu.com/> 能正常加载脚本

![image](https://user-images.githubusercontent.com/38517192/209086004-83739951-caaf-4c45-92e7-3fedb87c8018.png)

**Comment by lisonge** [comment]
可否把控制台报错日志截图看看？我无法复现你遇到的错误

**Comment by Sokwva** [comment]
> 可否把控制台报错日志截图看看？我无法复现你遇到的错误

<img width="730" alt="屏幕截图 2022-12-22 160101" src="https://user-images.githubusercontent.com/25543370/209086518-6ba66f76-387a-4d1e-8297-93a7160082ba.png">

就只有一行报错，刚刚使用的暴力猴也是如此的报错，只不过暴力猴会在安装的时候提示需要在match的结尾加上/

**Comment by lisonge** [comment]
查看 `Devtools` - `元素` 一栏看看第一个`script`标签是否和截图里的一致呢

![image](https://user-images.githubusercontent.com/38517192/209087282-b2d94acd-ccc6-4d65-bf60-2a6bbd5a12d2.png)

**Comment by lisonge** [comment]
也许是 node 版本问题？请问你的 node 版本是多少呢

**Comment by Sokwva** [comment]
第一个script标签内容不一致，node版本是v18.12.1

**Comment by lisonge** [comment]
> 第一个script标签内容不一致

那么这个 script 标签的 text 属性是什么呢？

> node版本是v18.12.1 

当我使用 node@18.12.1 时，我仍然没有复现你的错误

**Comment by Sokwva** [comment]
> > 第一个script标签内容不一致
> 
> 那么这个 script 标签的 text 属性是什么呢？
> 
> > node版本是v18.12.1
> 
> 当我使用 node@18.12.1 时，我仍然没有复现你的错误

抱歉，刚刚看错了，script标签内容是一致的，我刚刚使用其他的系统测试了一下（Windows 10 LTSB 21H1，Edge，油猴，Node v18.0.02）却没问题，应该是我这台电脑系统的环境问题。
<img width="473" alt="屏幕截图 2022-12-22 161418" src="https://user-images.githubusercontent.com/25543370/209088759-18227e1d-96b2-4841-b2fd-0d6659f7c556.png">

**Comment by Sokwva** [comment]
谢谢您的解答(ノﾟ∀ﾟ)ノ

**Comment by Sokwva** [comment]
刚刚对比了一下，右边是另一台可行的，左边是有问题的，好像明显少了很多文件
<img width="749" alt="屏幕截图 2022-12-22 164700" src="https://user-images.githubusercontent.com/25543370/209094806-53166cf0-7eda-4cd4-bf0c-be062b259909.png">

**Comment by lisonge** [comment]
你可以尝试使用 [pnpm](https://pnpm.io/zh/installation) 管理依赖

![image](https://user-images.githubusercontent.com/38517192/209095409-55fb466d-e75f-470c-bd59-1a64b62226c8.png)

**Comment by Sokwva** [comment]
> 你可以尝试使用 [pnpm](https://pnpm.io/zh/installation) 管理依赖
> 
> ![image](https://user-images.githubusercontent.com/38517192/209095409-55fb466d-e75f-470c-bd59-1a64b62226c8.png)

我晚上将之前那一台能成功的电脑的环境切换到18.12并切换到pnpm时，终于也出现了一样的状况了･ﾟ( ﾉヮ´ )，确实是环境问题
