### ISSUE TITLE
拒绝执行内联脚本

### ISSUE THREAD

**Issue by Hunlongyu** [lisonge/vite-plugin-monkey#39]
vite.config.js
```js
import { defineConfig } from 'vite';
import monkey from 'vite-plugin-monkey';
import eslintPlugin from 'vite-plugin-eslint';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    monkey({
      entry: 'src/main.js',
      userscript: {
        icon: 'https://vitejs.dev/logo.svg',
        namespace: 'npm/vite-plugin-monkey',
        match: ['*://github.com/*'],
        'run-at': 'document-end',
      },
    }),
    eslintPlugin(),
  ],
});
```
main.js
```js
console.log('lala');
```

![image](https://user-images.githubusercontent.com/15273630/210710637-49cf7f85-518f-4ee6-bb1f-7793626cbfe4.png)

报错文字如下：
> userscript.html?name=server%253Agithub.user.js&id=8a1c944e-1d66-47f8-8d2c-fb2eef8448a2:79 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' github.githubassets.com". Either the 'unsafe-inline' keyword, a hash ('sha256-m9WuhxCDjalzF2tBhg/f0YTfasIeLnFGhEK6+zp1IZw='), or a nonce ('nonce-...') is required to enable inline execution.

如果说 github 做了限制，那么其他脚本应该也无法正常运行。但我只是简单的加了一个 `console.log` 就无法运行，感觉是不是哪里出问题了。

**Comment by lisonge** [comment]
![image](https://user-images.githubusercontent.com/38517192/210711938-7e943d15-e70c-4159-a6c9-5ae14a94d6fe.png)

https://github.com/lisonge/vite-plugin-monkey#csp

**Comment by lisonge** [comment]
![image](https://user-images.githubusercontent.com/38517192/210712238-2e661ab5-60e5-4f5d-b675-dee9d7df9379.png)

**Comment by Hunlongyu** [comment]
感谢已解决
