### ISSUE TITLE
使用unocss打包后报错

### ISSUE THREAD

**Issue by viarotel** [lisonge/vite-plugin-monkey#45]
![image](https://user-images.githubusercontent.com/38282758/221135191-d10ea2de-b428-4209-9e47-366bda85c6ca.png)

**Comment by viarotel** [comment]
应该是 "*,:before,:after{--un-rotate:0;................................................"

**Comment by lisonge** [comment]
![image](https://user-images.githubusercontent.com/38517192/221140018-23db92d1-7763-49b6-a81d-d5b02c2ec73c.png)

不好意思，我没有复现，可否把你的最小复现demo上传至github

**Comment by viarotel** [comment]
[min-project.7z.gz](https://github.com/lisonge/vite-plugin-monkey/files/10822738/min-project.7z.gz)

**Comment by viarotel** [comment]
> [min-project.7z.gz](https://github.com/lisonge/vite-plugin-monkey/files/10822738/min-project.7z.gz)

解压前去掉".gz"

**Comment by lisonge** [comment]
把 ` useUnocss(),` 放到 `useMonkey` 前面就行

```js
import path from 'node:path'
import { defineConfig } from 'vite'
import useVue from '@vitejs/plugin-vue'
import useMonkey, { cdn, util } from 'vite-plugin-monkey'
import useEslint from 'vite-plugin-eslint'
import useUnocss from 'unocss/vite'
// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src/'),
    },
  },
  plugins: [
    useVue(),
    useUnocss(),
    useMonkey({
      entry: 'src/main.js',
      userscript: {
        name: 'min-project',
        author: 'viarotel',
        namespace: 'viarotel/min-project',
        description: 'min-project',
        version: '0.0.1',
        icon: 'https://vitejs.dev/logo.svg',
        require: [],
      },
      build: {
        externalGlobals: {
          vue: cdn.jsdelivr('Vue', 'dist/vue.global.prod.js').concat(
            await util.fn2dataUrl(() => {
              // @ts-ignore
              // eslint-disable-next-line no-undef
              window.Vue = Vue
            }),
          ),
        },
      },
    }),
    useEslint({ fix: true }),
  ],
})

```

**Comment by viarotel** [comment]
> 把 ` useUnocss(),` 放到 `useMonkey` 前面就行
> 
> ```js
> import path from 'node:path'
> import { defineConfig } from 'vite'
> import useVue from '@vitejs/plugin-vue'
> import useMonkey, { cdn, util } from 'vite-plugin-monkey'
> import useEslint from 'vite-plugin-eslint'
> import useUnocss from 'unocss/vite'
> // https://vitejs.dev/config/
> export default defineConfig({
>   resolve: {
>     alias: {
>       '@': path.resolve(__dirname, './src/'),
>     },
>   },
>   plugins: [
>     useVue(),
>     useUnocss(),
>     useMonkey({
>       entry: 'src/main.js',
>       userscript: {
>         name: 'min-project',
>         author: 'viarotel',
>         namespace: 'viarotel/min-project',
>         description: 'min-project',
>         version: '0.0.1',
>         icon: 'https://vitejs.dev/logo.svg',
>         require: [],
>       },
>       build: {
>         externalGlobals: {
>           vue: cdn.jsdelivr('Vue', 'dist/vue.global.prod.js').concat(
>             await util.fn2dataUrl(() => {
>               // @ts-ignore
>               // eslint-disable-next-line no-undef
>               window.Vue = Vue
>             }),
>           ),
>         },
>       },
>     }),
>     useEslint({ fix: true }),
>   ],
> })
> ```

好的 按照这个方法确实有效 感谢大佬的指导

**Comment by lisonge** [comment]
一些补充

出现错误是因为
<https://github.com/unocss/unocss/blob/b1377a98e5b443dbec2c4bda166c9c0afbc04dfb/packages/vite/src/modes/global/build.ts#L267>
![image](https://user-images.githubusercontent.com/38517192/221156454-0f4e3daa-8f22-426f-a31e-a4f5bca8dd61.png)

执行了替换操作，替换使用的正则是

<https://github.com/unocss/unocss/blob/b1377a98e5b443dbec2c4bda166c9c0afbc04dfb/packages/shared-integration/src/layers.ts#L29>
![image](https://user-images.githubusercontent.com/38517192/221156694-a08ef145-7a5f-47ae-ac34-c05b374f613c.png)

就把 js 代码里的 `"` 给替换掉了

替换之前是

```txt
("#--unocss--{layer:__ALL__}#--unocss-layer-start--__ALL__--{start:__ALL__} *,::before
```

替换之后是

```txt
( *,::before
```
