### ISSUE TITLE
Support multiple userscripts

### ISSUE THREAD

**Issue by snordquist** [lisonge/vite-plugin-monkey#47]
```typescript
export default defineConfig(async ({ command, mode }) => ({
    plugins: [
        monkey({
            entry: 'src/entry1.ts',
            userscript: {
              // ...
            },
            build: {
                fileName: 'out1.user.js',
            },
        }),

        monkey({
            entry: 'src/entry2.ts',
            userscript: {
              // ...
            },
            build: {
                fileName: 'out2.user.js',
            },
        }),
  ]
```

Currently only `out2.user.js` is written, containing both userscript headers, which does not work with tampermonkey.

**Comment by lisonge** [comment]
vite has `vite build` and `vite serve` two mode, if you use `vite serve` , the number of entry must be one

if you just `build` multiple entry, you can use vite build api

```ts
// custom_build.ts
import { build } from 'vite';
import monkey from 'vite-plugin-monkey';

await build({
  plugins: [
    monkey({
      entry: 'src/entry1.ts',
      userscript: {
        namespace: 'namespace',
      },
      build: {
        fileName: 'out1.user.js',
      },
    }),
  ],
});
await build({
  plugins: [
    monkey({
      entry: 'src/entry2.ts',
      userscript: {
        namespace: 'namespace',
      },
      build: {
        fileName: 'out2.user.js',
      },
    }),
  ],
});
```

you can use [tsx](https://www.npmjs.com/package/tsx) run it

```shell
pnpm exec tsx ./custom_build.ts
```

**Comment by lisonge** [comment]
if you want to manage multiple userscript/package in single git repository

you can use monorepo, [pnpm monorepo](https://pnpm.io/zh/workspaces)  is a widely used one in its implementation

the following  repository all are based  `pnpm monorepo` 

- [userscripts](https://github.com/lisonge/userscripts)
- [vite-plugin-monkey](https://github.com/lisonge/vite-plugin-monkey)
- [vite](https://github.com/vitejs/vite)
- [vue](https://github.com/vuejs/vue)
- [element-plus](https://github.com/element-plus/element-plus)

such as [userscripts](https://github.com/lisonge/userscripts)

```shell
pnpm -F package_name serve
// startup one project serve script 

pnpm -r --filter=./packages/* serve
// startup all serve script

pnpm -F package_name build
// startup one project build

pnpm -r --filter=./packages/* build
// startup all build
```
