### ISSUE TITLE
Cannot build while there is another SSR plugin in the same config

### ISSUE THREAD

**Issue by Malix-Off** [lisonge/vite-plugin-monkey#53]
## Issue

I am developing a SvelteKit website which in I do host my Tampermonkey's userscripts.
I can't manage to make the plugin be built after I added my svelte website to the repo.

adding
```ts
rollupOptions: {
	output: {
		inlineDynamicImports: false,
	},
},
```
in the `build` vite config option doesn't work as SvelteKit:
```md
The following Vite config options will be overridden by SvelteKit:
  - build.rollupOptions.input
```

**Comment by Malix-Off** [comment]
- [Comment Reply](https://github.com/Tampermonkey/tampermonkey/issues/1717#issuecomment-1447220511) in https://github.com/Tampermonkey/tampermonkey/issues/1717 from @7nik:
  > [⋯](https://github.com/Tampermonkey/tampermonkey/issues/1717#issuecomment-1447220511) I had a really good experience using [vite-plugin-monkey](https://github.com/lisonge/vite-plugin-monkey) to develop and build a userscript (TS + Svelte in my case)

  Hello again @7nik!
  Do you think you could support me?

**Comment by lisonge** [comment]
you should make the order of vite plugin monkey is last one

if error again, you can try use the 3.0.0 plugin

**Comment by 7nik** [comment]
What are you trying to achieve by using SvelteKit in the userscript? It is a full-stack framework. SvelteKit is supposed to run on a server.
For making a userscipt with an advanced UI you need just Svelte (maybe with some router) but not SvelteKit.

**Comment by Malix-Off** [comment]
> you should make the order of vite plugin monkey is last one

It throw me this error
![image](https://user-images.githubusercontent.com/76160668/224106670-4903a5ed-3d3b-4a84-bf9a-677b36cc5069.png)

**Comment by Malix-Off** [comment]
@7nik 
> Using SvelteKit in the userscript?

Nope, I don't use SvelteKit in my userscript, I **host** the userscript on a svelte website (so only basically making it be downloadable from my website). Nothing svelte related does takes part in how I dev my userscript.

**Comment by 7nik** [comment]
If you are trying to build the website and all the userscripts in one command, I'm not sure it's possible - they conflict.
Maybe you need two configs - one for the website, and another for userscripts. And sequentially run to builds.

**Comment by lisonge** [comment]
@Malix-Off 

vite-plugin-monkey can not work with vite ssr plugin such as SvelteKit

**Comment by Malix-Off** [comment]
@lisonge @7nik
I succeeded to make it build correctly with this `vite.config.ts` file:

## `vite.config.ts`
```ts
import { defineConfig } from 'vite';
import { sveltekit } from '@sveltejs/kit/vite';
import monkey from 'vite-plugin-monkey';

const userscriptBuildConfig = defineConfig({
	plugins: [
		monkey({
			entry: 'external/script.user.ts',
			userscript: {
				namespace: 'https://github.com/EFRAUDE/Moodle',
			},
		}),
	],
});

const sveltekitBuildConfig = defineConfig({
	plugins: [
		sveltekit(),
	],
});

// https://vitejs.dev/config/
export default ( {mode}: {mode: string} ) => {
	console.log(mode);
	switch (mode) {
		case ('userscript'):
		case ('script'):
			return userscriptBuildConfig;
		case ('website'):
		case ('site'):
			return sveltekitBuildConfig;
		default:
			return userscriptBuildConfig && sveltekitBuildConfig;
	}
};
```

But unfortunately, the fact that it is two different builds remove the Tampermonkey's metadata comments
![image](https://user-images.githubusercontent.com/76160668/224166120-ebebdd25-b092-48f6-91f1-fc3669e59e6b.png)

So it is not really working properly.
Can you explain why it isn't possible to do it with one build?

**Comment by 7nik** [comment]
```js
default:
	return userscriptBuildConfig && sveltekitBuildConfig;
```
Note this code returns only the second config. It does not run two builds.

For me, it looks like SvelteKit treated the userscript as a regular script.

Try to output the userscript into the `static` folder.

**Comment by Malix-Off** [comment]
> ```js
> default:
> 	return userscriptBuildConfig && sveltekitBuildConfig;
> ```
> 
> Note this code returns only the second config. It does not run two builds.

Nope, just tested it and it runs the two builds

**Comment by Malix-Off** [comment]
> ```js
> default:
> 	return userscriptBuildConfig && sveltekitBuildConfig;
> ```
> 
> Note this code returns only the second config. It does not run two builds.

You're right.
Do you know how to make it run both?

**Comment by 7nik** [comment]
For command `npm run build` with the script `build` being `"vite build"`?

**Comment by Malix-Off** [comment]
> For me, it looks like SvelteKit treated the userscript as a regular script.

As it should be, but at the same time not very much since as @lisonge said:
> vite-plugin-monkey can not work with vite ssr plugin such as SvelteKit

**Comment by Malix-Off** [comment]
> Try to output the userscript into the `static` folder.

May I ask you where should that be inputed in the code I provided?

**Comment by Malix-Off** [comment]
> For command `npm run build` with the script `build` being `"vite build"`?

![image](https://user-images.githubusercontent.com/76160668/224173004-c711e27b-ae60-44c5-b585-974528f95bdb.png)

Basically I used `npx vite build -m INPUT_MODE`

**Comment by 7nik** [comment]
`A && B` is the same as `A ? B : A` and as objects always are truthy, it will return `B`.

Put the `static` folder into the root of your project folder. It's the default folder for assets in SvelteKit. The files will be available as `site.name/filename.extension` on the site. You can add subfolders there as well.

**Comment by Malix-Off** [comment]
> `A && B` is the same as `A ? B : A` and as objects always are truthy, it will return `B`.

You're right, i'm very dumb, thx about that.

> the `static` folder into the root of your project folder.

What should I put inside it?
The raw ts script, or the built output one?

**Comment by 7nik** [comment]
Out the compiled userscripts into the `static` so during the website building, it will just copy them without any modifications.

**Comment by Malix-Off** [comment]
> Out the compiled userscripts into the `static` so during the website building, it will just copy them without any modifications.

Okay, so if I understand correctly, I have to do two builds:

1. Userscript Build
  - Output in `static`
2. Website Build
  - With reference to the path to the built userscript in `static`

Is that correct?

**Comment by 7nik** [comment]
> * With reference to the path to the built userscript in `static`

Not sure I got it right.

For a file like `static/some-name.user.script.js`, you reference it as `site.name/some-name.user.script.js`.
The rest is correct.

Technically you can skip the second build if there are no changes on the site and just update userscripts.

**Comment by Malix-Off** [comment]
> Not sure I got it right.
> 
> For a file like `static/some-name.script.user.js`, you reference it as `site.name/some-name.script.user.js`.

I was talking about the reference as file path, not the URL ahah, but ye, I got it :)

> Technically you can skip the second build if there are no changes on the site and just update userscripts.

Nice, that's what I thought in my second thought.
Imma try to build that then.
Thanks!

**Comment by lisonge** [comment]
@Malix-Off 

>Could you explain why?
It doesn't really makes sense to me why it couldn't work as it's a regular build with not much happening at the pluggin level (at least compared to how SvelteKit interacts with the build)

The construction mode and configuration of `sveltekit` and `vite-plugin-monkey` conflict

just like make vite both build  `browser web app` and `ssr app`  in the same config

**Comment by Malix-Off** [comment]
I now have yet another problem with this double config method: #54
