### ISSUE TITLE
minified build are unusable

### ISSUE THREAD

**Issue by Malix-Off** [lisonge/vite-plugin-monkey#56]
Discussed in #55

Caused by https://github.com/Tampermonkey/tampermonkey/issues/1567

**Comment by lisonge** [comment]
fix it in [v3.0.0-alpha.2](https://github.com/lisonge/vite-plugin-monkey/releases/tag/v3.0.0-alpha.2)

**Comment by Malix-Off** [comment]
> fix it in [v3.0.0-alpha.2](https://github.com/lisonge/vite-plugin-monkey/releases/tag/v3.0.0-alpha.2)

By https://github.com/lisonge/vite-plugin-monkey/commit/394500def6b6e8c85afb4e8b343b7d8b989d1de0

**Comment by Malix-Off** [comment]
> fix it in [v3.0.0-alpha.2](https://github.com/lisonge/vite-plugin-monkey/releases/tag/v3.0.0-alpha.2)

How did you fixed it?

**Comment by lisonge** [comment]
> How did you fixed it?

get it by Identifier instead of MemberExpression

**Comment by lisonge** [comment]
[v3.0.0](https://github.com/lisonge/vite-plugin-monkey/releases/tag/v3.0.0)

**Comment by Malix-Off** [comment]
@lisonge I'm not sure but I think you made a bug where the entry points leaks, but imma check and keep you in touch.

**Comment by Malix-Off** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/1567#issuecomment-1466829927
