### ISSUE TITLE
不支持 GM_cookie

### ISSUE THREAD

**Issue by imbytecat** [lisonge/vite-plugin-monkey#6]
在用的 Tampermonkey BETA 的一个特性，似乎这里不支持。

![GM_cookie_not_supported](https://user-images.githubusercontent.com/15844288/181769347-314244c3-d30f-4dc4-bacc-d216cab19892.jpg)

**Comment by lisonge** [comment]
@imbytecat 

```ts
import { defineConfig } from 'vite';
import monkey from 'vite-plugin-monkey';

// https://vitejs.dev/config/
export default defineConfig(({ command, mode }) => ({
  plugins: [
    monkey({
      entry: 'src/main.ts',
      userscript: {
        name: 'name',
        namespace: 'https://github.com/lisonge',
        version: '1.0.1',
        grant: ['GM.addElement'],
        $extra: {
          grant: ['GM_cookie'],
        },
      },
    }),
  ],
}));
```

**Comment by lisonge** [comment]
感谢提醒，后续版本会添加类型提示

**Comment by imbytecat** [comment]
即使在 `$extra` 中添加了对应的方法似乎也无法正常使用吗？我在浏览器中调用的时候遇到了一些问题：

![GM_cookie_is_not_defined](https://user-images.githubusercontent.com/15844288/181789651-3c32d1aa-59a2-4207-ad43-1c7cb9548b46.jpg)

另外，这些内置方法暂时还没有类型提示吗，还是需要另外引入 types 文件？我这边 TypeScript 全部报错了，好难过 o(╥﹏╥)o

![cannot_use_internal_functions](https://user-images.githubusercontent.com/15844288/181790000-e4038fcd-5c84-4faf-bcc9-ff9c2b47fbbb.jpg)

**Comment by lisonge** [comment]
第一个问题，注入GM的方法是固定的，你需要手动需要更换注入模板，我一会会修复这个

第二个问题，类型声明在这个本库的package.json 的peers依赖

**Comment by imbytecat** [comment]
> 第一个问题，注入GM的方法是固定的，你需要手动需要更换注入模板，我一会会修复这个
> 
> 第二个问题，类型声明在这个本库的package.json 的peers依赖

谢谢，第二个问题安装了 `@types/tampermonkey` 就没问题了。

很棒的项目，已 Star！

**Comment by lisonge** [comment]
fixed -> <https://github.com/lisonge/vite-plugin-monkey/blob/v1.1.4/packages/vite-plugin-monkey/CHANGELOG.md#bug-fixes>
由于 `GM_cookie` 属于 beta 的特性，故没有添加 `GM_cookie` 的类型注释，仍然需要通过以下方式添加
```ts
import { defineConfig } from 'vite';
import monkey from 'vite-plugin-monkey';

export default defineConfig(({ command, mode }) => ({
  plugins: [
    monkey({
      entry: 'src/main.ts',
      userscript: {
        name: 'name',
        namespace: 'https://github.com/lisonge',
        version: '1.0.1',
        grant: ['GM.addElement'],
        $extra: {
          grant: ['GM_cookie'],
        },
      },
    }),
  ],
}));
```
vite serve 模式下，会将 以下字段和 `$extra.grant` 添加的字段 获取到的对象挂载到 `unsafeWindow` 

```json5
[
        'GM',
        'GM_addElement',
        'GM_addStyle',
        'GM_addValueChangeListener',
        'GM_deleteValue',
        'GM_download',
        'GM_getResourceText',
        'GM_getResourceURL',
        'GM_getTab',
        'GM_getTabs',
        'GM_getValue',
        'GM_info',
        'GM_listValues',
        'GM_log',
        'GM_notification',
        'GM_openInTab',
        'GM_registerMenuCommand',
        'GM_removeValueChangeListener',
        'GM_saveTab',
        'GM_setClipboard',
        'GM_setValue',
        'GM_unregisterMenuCommand',
        'GM_xmlhttpRequest',
      ]
```

**Comment by lisonge** [comment]
supported by <https://github.com/lisonge/vite-plugin-monkey/commit/a603ae3750a86f3193d8a3cbfb9310d793a776e8>
v2 预发布：GM_api 现在可以通过 ESM 导入的方式使用，自带类型提示/文档，综合 tampermonkey/violentmonkey/greasemonkey 三者的 类型提示

```ts
import { GM_cookie, unsafeWindow, monkeyWindow } from '$';
```

**Comment by lisonge** [comment]
fixes by <https://github.com/lisonge/vite-plugin-monkey/blob/v2.0.0/packages/vite-plugin-monkey/CHANGELOG.md#200-features>
