### ISSUE TITLE
`GM_webRequest` removed for now

### ISSUE THREAD

**Issue by Malix-Off** [lisonge/vite-plugin-monkey#64]
![image](https://user-images.githubusercontent.com/76160668/226483327-12620435-954a-4ef7-9f39-1b181cef6c82.png)

See https://github.com/Tampermonkey/tampermonkey/issues/1086#issuecomment-1408488243 leading to https://github.com/Tampermonkey/tampermonkey/issues/397

**Comment by lisonge** [comment]
> GM_webRequest removed for now

emmm, where is the description of `removed` ?

**Comment by lisonge** [comment]
I add `GM_webRequest` to client because there is GM_webRequest at [api:GM_webRequest](https://www.tampermonkey.net/documentation.php#api:GM_webRequest)

and it can be used in code

![image](https://user-images.githubusercontent.com/38517192/226553075-0c56aad4-983d-44e4-a8ea-0fb33337ff4b.png)

---

So what should I do ？

**Comment by Malix-Off** [comment]
> I add `GM_webRequest` to client because there is GM_webRequest at [api:GM_webRequest](https://www.tampermonkey.net/documentation.php#api:GM_webRequest)
> 
> and it can be used in code
> 
> ![image](https://user-images.githubusercontent.com/38517192/226553075-0c56aad4-983d-44e4-a8ea-0fb33337ff4b.png)
> 
> ---
> 
> So what should I do ？
> 
> 

Ah that's weird.
Do you think the in-editor error message is a false-positive and should be removed then?
If yes, I'm going to open an issue in their repository

**Comment by Malix-Off** [comment]
What happen when you remove the "grant" meta line in the code in your screenshot?

**Comment by Malix-Off** [comment]
Ye, then I think the error message is a bug.
I will open an issue in their repository
