### ISSUE TITLE
any way to use vm-dom for "vanilla" JSX?

### ISSUE THREAD

**Issue by Wulfre** [lisonge/vite-plugin-monkey#68]
There is a package developed by the same people as violentmonkey for transforming JSX into "vanilla" elements but I am not sure if there is a way to use it along with vite and this plugin, but it may be something worth investigating.

https://github.com/violentmonkey/vm-dom

**Comment by lisonge** [comment]
This question has nothing to do with vite-plugin-monkey

<https://vitejs.dev/guide/features.html#jsx>

<https://github.com/lisonge/vite-plugin-monkey/blob/73d6db261ec12f3e8aac595aed342d72ca3c2a9b/playground/vm-dom/vite.config.ts#L1-L27>

<https://github.com/lisonge/vite-plugin-monkey/blob/73d6db261ec12f3e8aac595aed342d72ca3c2a9b/playground/vm-dom/src/main.tsx#L1-L10>

<https://github.com/lisonge/vite-plugin-monkey/blob/73d6db261ec12f3e8aac595aed342d72ca3c2a9b/playground/vm-dom/dist/vm-dom.user.js#L1-L40>
