### ISSUE TITLE
初始项目中 CSS 错误

### ISSUE THREAD

**Issue by wdssmq** [lisonge/vite-plugin-monkey#7]
Search · 1a1a1a：

[https://github.com/lisonge/vite-plugin-monkey/search?q=1a1a1a](https://github.com/lisonge/vite-plugin-monkey/search?q=1a1a1a "Search · 1a1a1a")

`background-color: #1a1a1a;` → `border-color: #1a1a1a`;

目测这里是想定义边框样式……

**Comment by lisonge** [comment]
不好意思，没看明白，css 的什么错误？是有语法错误吗？
这个项目的脚手架内部代码来自 <https://github.com/vitejs/vite/tree/main/packages/create-vite>
我主要做了以下改动
- 移除 index.html 的 script 入口 挂载 dom
- vite.config.ts/js 内加入 vite-plugin-monkey 的基本配置，包括入口
- 替换模板项目内框架的挂载节点为添加节点
- 删除 public 目录，移动 vite.svg 到 src/assets 目录，并更改 静态资源引用方式

你想表达的意思是 脚手架 demo 模板不规范吗？

这只是一个脚手架，创建之后是需要按照自己的需求改的，里面的代码样式是什么不重要

**Comment by wdssmq** [comment]
那么这个官方样式就不适合作为当前项目的 demo，在谷歌的页面内会得到一个黑底黑字的按钮；

**Comment by lisonge** [comment]
哎呀，它就是个 **证明 vite-plugin-monkey 功能可行性** 的 demo 啊

就 业务实用性和ui观赏性 而言，它屁用没有

唯一的用处就是展示和各个框架的搭配使用，以及快速创建模板后供别人按照自己需求修改而不是 npm 一个一个慢慢装依赖

它是被用来二次修改的，不是用来直接使用的

**Comment by liutianjia** [comment]
select * from ZNZZ-DEV order by age limit 1

**Comment by wdssmq** [comment]
不是好不好看，而是那个黑底黑字的按钮实质上妨碍了我熟悉这个东西的进度；

或者可以另外实现一个创建真正空项目的命令：

pnpm create monkey:empty # 具体语法我并不太懂，

直接不包含我在 #8 中列出的文件，而只有一个空白的 main.js

-----------

还有一个实际影响使用的问题，我现在知道文档里有 csp 的内容，那么建议在 issues 置顶一个说明指向这里

**Comment by lisonge** [comment]
好的，我懂你的意思了
1. 关于模板：我后续会新建一个模板 pure-js/pure-ts 里面只有 main.js/main.ts
2. 关于csp，可行，另外在此附加完整说明 <https://github.com/lisonge/vite-plugin-monkey/blob/36ff3426d7d473f1c6c7b74dd68048787adad812/README_zh.md#csp>

**Comment by lisonge** [comment]
@wdssmq 

新模板： [template-empty](https://github.com/lisonge/vite-plugin-monkey/tree/create-monkey%401.1.5/packages/create-monkey/template-empty) ,  [template-empty-ts](https://github.com/lisonge/vite-plugin-monkey/tree/create-monkey%401.1.5/packages/create-monkey/template-empty-ts)

**Comment by wdssmq** [comment]
> @wdssmq
> 
> 新模板： [template-empty](https://github.com/lisonge/vite-plugin-monkey/tree/create-monkey%401.1.5/packages/create-monkey/template-empty) , [template-empty-ts](https://github.com/lisonge/vite-plugin-monkey/tree/create-monkey%401.1.5/packages/create-monkey/template-empty-ts)
> 
> 另外，便捷创建的命令，与 create-vite 一致
> 
> ```shell
> pnpm create vite my-empty-app --template empty
> ```

/赞

然后我这边也完成了一个自用脚本的更新，模块化加热重载确实方便不少。。
