### ISSUE TITLE
 @run-at document-start  will fail when in dev mode

### ISSUE THREAD

**Issue by ZhaoCabin** [lisonge/vite-plugin-monkey#73]
when I use some XHR Hook,  it must be run at document-start ，
but In  dev mode ， it acture run at document-end

how to fix this problem?

**Comment by lisonge** [comment]
set `monkeyConfig.userscript['run-at']='document-start'`

or use `chrome-remote-interface`, the usage is <https://github.com/lisonge/vite-plugin-monkey/discussions/60#discussioncomment-5328945>

**Comment by lisonge** [comment]
Is the problem solved now?

**Comment by ZhaoCabin** [comment]
> Is the problem solved now?

Yes, this is the same problem, thank you very much for your help, this helped me a lot, before that I was still frequently using yarn build to develop
