### ISSUE TITLE
开发模式下怎么引入@require的脚本资源

### ISSUE THREAD

**Issue by ZhaoCabin** [lisonge/vite-plugin-monkey#76]
比如有些hook的方法，我需要让他在 @require阶段就导入

我尝试使用window来传递模块
window.cbAjaxHooker = function() {)()

但实际项目中window和油猴脚本的window隔离了，window.cbAjaxHooker为undefined

我猜测应该是调试模式采用插入script标签的方式，导致无法识别@require资源，window也没法传递

请问这种情况我应该怎么在项目中使用 @require的方法

**Comment by lisonge** [comment]
> window也没法传递

```ts
import { monkeyWindow } from '$';
console.log(monkeyWindow.cbAjaxHooker)
```

**Comment by ZhaoCabin** [comment]
厉害，厉害，我就说这么厉害的框架不应该没有考虑这个的问题的
