### ISSUE TITLE
shadow-dom 模式下 css 不挂载到全局

### ISSUE THREAD

**Issue by mokeyish** [lisonge/vite-plugin-monkey#77]
这个插件不错👍，先前是自己写 vite 脚本调整的，但是 dev 模式并不好，看到你这个插件，想切换过来。但是发现这个插件默认把样式注入到全局了，没看到关的地方。对于油猴插件为了不受全局样式影响，shadow-dom 是不错的选择。因此需要把样式替换到 `/* global-placeholder */` 占位符上。

两个方案
1. 关闭此插件的 css 全局注入
2. 集成 shadow-dom 模式的 `/* global-placeholder */` 占位符替换。

---
怎么快速让样式插入到我这个占位符上呢？

![图片](https://user-images.githubusercontent.com/16131917/233651850-f6ff08cf-d38e-4847-9f94-7ae90147d18d.png)

先前写过的脚本。

```typescript


const bundle = (mode: string): PluginOption => {
  const placeholder = '/* global-placeholder */';
  let global_css: string | null = null;
  return {
    name: 'build:bundle',
    enforce: 'post',
    async buildStart() {
      global_css = null
    },
    generateBundle(_options, bundle) {
      console.log('');
      console.log('=======>', Object.keys(bundle));

      const css_assets = Object.values(bundle).map(o => o.type === 'asset' && o.fileName.endsWith('.css') ? o : undefined).filter(o => o !== undefined);
      if (css_assets.length > 0) {
        global_css = css_assets.map(o => (typeof o.source === 'string' ? o.source : new TextDecoder().decode(o.source)).trim()).join(' ').replace(/\\/g, '\\\\') ?? '';
      }

      if (!global_css) {
        return;
      }

      let replaced = false;
      for (const chunk of Object.values(bundle)) {

        if (chunk.type === 'chunk') {
          const code = typeof chunk.code === 'string' ? chunk.code : new TextDecoder().decode(chunk.code);
          if (code.includes(placeholder)) {
            chunk.code = `${banner}${code.replace(placeholder, global_css)}`;
            replaced = true;
          }
        }
      }

      if (mode === 'production' && replaced) {
        for (const key of Object.keys(bundle)) {
          const file = bundle[key];
          if (file.type === 'asset' && file.fileName.endsWith('.css')) {
            delete bundle[key];
          }
        }
      }

    }
  }
};


```

**Comment by mokeyish** [comment]
![图片](https://user-images.githubusercontent.com/16131917/233668297-6aac72ee-8488-4b3e-8d96-9ed9ab3303b9.png)

我实现了 Build 的 placeholder 替换，请问 serve dev 下的替换怎么搞？

**Comment by mokeyish** [comment]
@lisonge  你好，我提交了 PR，请指导下，怎么让 placeholder 在 vite serve dev 下生效？

**Comment by lisonge** [comment]
你的改动会造成 serve 与 build 模式下的行为不一致 

`import './xxx.css'` 这类代码被 vite 视为全局样式

vite 目前暂未支持 shadow-dom 下 css  <https://github.com/vitejs/vite/pull/12206>

目前看起来 shadow-dom 下的 css 只能使用 `css?inline` 实现，而且失去了 hmr

```ts
import cssText from './style.css?inline';

const style = document.createElement('style');
style.textContent = cssText;
shadow.appendChild(style);
```

**Comment by lisonge** [comment]
vite 下使用 Web components 的 lit 示例

[template-lit-ts/src/my-element.ts](https://github.com/vitejs/vite/blob/e7924d22f70fdfdab32b4aab224cd66317f3c768/packages/create-vite/template-lit-ts/src/my-element.ts#L50-L120)

也是使用 内联 css

**Comment by mokeyish** [comment]
我用了 unocss ，没有单独的 style.css 文件，是动态生成的。

**Comment by mokeyish** [comment]
unocss 的 shadow-dom 的 placeholder 也好像有问题，它只管那个组件文件的 css，像油猴插件，其实就是最外层的组件才是 shadow-dom，需要把所有样式收集，放到 shadow–dom 的 `<style>标签里</style>`.

**Comment by lisonge** [comment]
你为什么不在 vite-plugin-monkey 前面加一个插件把 css 移动到 js 里

好像没必要修改  vite-plugin-monkey 源代码

**Comment by mokeyish** [comment]
嗯，好像也可以。把我之前写的脚本放在  vite-plugin-monkey 之前就行了。到  vite-plugin-monkey 就没 css 给它注入了。

build 和 serve 行为不一致，你有什么思路，也通过插件来快捷的解决吗？上面你引用的 PR 貌似没那么容易合并。

**Comment by mokeyish** [comment]
谢谢你的耐心解答，我改成这样完美解决了，开发模式去 Head 上取样式，放到 shadow dom 里，生产模式就用 placeholder 替换。

SolidJs 完美啊，代码可以写的这么简洁。


![图片](https://user-images.githubusercontent.com/16131917/233691081-bbdcc6d2-087b-4a52-b0c2-5003b70c7c2e.png)

**Comment by lisonge** [comment]
如果 unocss 支持直接导出 原生 style 对象，生产模式 额外的插件 也不需要了

```ts
import unocssStyle from 'virtual:uno.css?style';

render(
  () => (
    <Portal useShadow>
        {unocssStyle}
        <App />
      </Portal>
  ),
  document.body,
);```

**Comment by mokeyish** [comment]
我上面的写法相当于启动后将 head 里的 styledom 对象移动到了 shadowdom 里，hmr 也都正常。

**Comment by yunsii** [comment]
使用 unocss 现在看起来现在还是得自行处理才能更好的 HMR？

**Comment by lisonge** [comment]
https://github.com/unocss/unocss/pull/2570#issuecomment-1666584117

**Comment by UnluckyNinja** [comment]
我也遇到类似情况，用UnoCSS，外面套一层shadowDOM，但用的内联样式。
研究了几天，目前热更新和构建都可以了，但单文件组件内的style块不知道怎么引入到代码里，还没想到好的办法。
大致上就是UnoCSS里面加了一下内联的判断（默认情况resolveId阶段会把query丢掉），修改了virtual:uno.css转换使其兼容UnoCSS的HMR转换，然后开发模式下触发模块重载，构建模式下在JS里替换，详细方式写在这里了：https://github.com/unocss/unocss/issues/4137#issuecomment-2501112854 ，供各位参考
