### ISSUE TITLE
是否有方法可以使多个UserScript在同一目录下开发？

### ISSUE THREAD

**Issue by LinLin00000000** [lisonge/vite-plugin-monkey#82]
我不想使用 monorepo 那一套东西，我想直接在单个目录（比如“src”）中开发多个脚本，vite配置大概像这样
![image](https://github.com/lisonge/vite-plugin-monkey/assets/51076594/623677e8-3f1f-47fb-8681-063ccf9c7e98)
不想引入很多资源、包做个大工程，只想做点小东西，有没有方便的方法实现这样简单便捷的开发方式呢？

**Comment by lisonge** [comment]
vite.config.script1.ts 
```shell
vite --config vite.config.script1.ts 
```

vite.config.script2.ts
```shell
vite --config vite.config.script2.ts 
```

vite.config.script2.ts
```shell
vite --config vite.config.script3.ts 
```

**Comment by LinLin00000000** [comment]
有一个问题，构建多个script时，后一个的构建产物会覆盖前一个，即使 build.fileName 不一样。
并行构建的话有时可以顺利构建多个，有时就只剩一个文件了😢

**Comment by LinLin00000000** [comment]
又遇到一个问题，vite preview 时会进行脚本安装，但当 dist 目录下有多个 userscript 时只会安装其中一个。

我试着修复了一下。 #83

**Comment by LinLin00000000** [comment]
感谢作者的耐心解答和光速回复，问题已解决。

我直接调用 vite 的 build、preview API 实现了一个简单的构建脚本，可以方便我的小脚本快速开发😊
https://github.com/LinLin00000000/L-UserScript/blob/main/index.js

**Comment by uulll** [comment]
请问，通过vite.config.script1.ts配置之后，是通过npm run build 命令打包还是什么呢。
![image](https://github.com/lisonge/vite-plugin-monkey/assets/30826164/186a50df-bb2f-432a-9194-8d64460955ad)
这是我的目录结构，报错了：RollupError: Could not resolve entry module "index.html".

**Comment by lisonge** [comment]
https://cn.vitejs.dev/guide/cli.html

**Comment by lisonge** [comment]
```shell
vite build --config vite.config.script1.ts 
```

**Comment by uulll** [comment]
感谢你的回复，但是我仍然遇到问题。
![image](https://github.com/lisonge/vite-plugin-monkey/assets/30826164/26870145-1420-4b7f-9c76-a1fb75ccf019)

![image](https://github.com/lisonge/vite-plugin-monkey/assets/30826164/826bb894-dad9-430c-8573-7e2a12fca366)

请帮忙看看是哪里出了问题。感谢！！

**Comment by lisonge** [comment]
`--config`

**Comment by uulll** [comment]
原谅我的粗心。我确实非常菜，在请教一个问题，viteConfig.build.emptyOutDir=false这个配置是在哪里的呢。我也遇到了build之后，文件覆盖的问题

**Comment by uulll** [comment]
非常感谢！！！

**Comment by uulll** [comment]
大佬，在请教一下，有没有类似于 vite build --config  * 之类的语法，希望能将多个脚本一起打包

**Comment by lisonge** [comment]
```txt
vite build --config vite.config1.ts && vite build --config vite.config2.ts
```

**Comment by uulll** [comment]
看来只能用批处理做了。 分享一下：for /r  %i in (vite.config.*.js) do ( npx vite build -c   %i )
