### ISSUE TITLE
构建生成的JS代码目标版本问题

### ISSUE THREAD

**Issue by JianJroh** [lisonge/vite-plugin-monkey#85]
目前使用插件打包生成的代码都是ES5版本且没有进行最大程度的minify（与vite默认构建相比），是否可以遵循开发者定义的目标版本

**Comment by lisonge** [comment]
> 目前使用插件打包生成的代码都是ES5版本

使用的是 vite 默认的 target ，不是 ES5

---

> 且没有进行最大程度的minify（与vite默认构建相比）

因为 greasyfork 的策略不允许 minify 代码，所以插件更改了默认值

<https://github.com/lisonge/vite-plugin-monkey/blob/060b33eaf68850d7b8f111d25a76b50aad49d9cb/packages/vite-plugin-monkey/src/node/index.ts#L56>

配置 vite.config.ts 的 `viteConfig.build.minify=true` 即可启用

**Comment by lisonge** [comment]
请问还有疑问吗？
