### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by limin2017** [lisonge/vite-plugin-monkey#9]
使用除vue外引入其他cdn的情况，开发环境正常，打包后无法正常运行。
![image](https://user-images.githubusercontent.com/26949167/183242269-d2ccf871-e672-4445-be05-287254efbf4c.png)

**Comment by limin2017** [comment]
![image](https://user-images.githubusercontent.com/26949167/183242313-1e3333aa-2c68-42be-926c-24e8c4c25a2f.png)

**Comment by lisonge** [comment]
请展示具体错误，另外貌似你的问题和 <https://github.com/lisonge/vite-plugin-monkey/issues/5> 差不多

**Comment by lisonge** [comment]
应该是一样的问题，Vue 使用 iife 格式 ，element-plus 使用 umd 格式，这两个格式在油猴脚本环境中 无法共同加载

**Comment by lisonge** [comment]
看起来是一个高频问题，确实需要在文档中说明一下
另外我看看能不能尝试在 build.checkCDN === true 的情况下，去检测 这些 cdn 的格式是否是统一的格式

**Comment by lisonge** [comment]
@limin2017 能把打包之后的代码贴出来吗？我得确认一下是不是这个问题
