### ISSUE TITLE
`GM_registerMenuCommand` 无法在 dev 模式下使用

### ISSUE THREAD

**Issue by Sec-ant** [lisonge/vite-plugin-monkey#91]
在开发[这个脚本](https://github.com/Sec-ant/weread-scraper)的过程中发现无法在 dev 模式下调出由 `GM_registerMenuCommand` 注册的 GM 脚本菜单，但是 build 后的脚本是可以的，想请教一下原因是什么？

![image](https://github.com/lisonge/vite-plugin-monkey/assets/10386119/5b773d5e-c728-413a-8451-00fd99c289af)

**Comment by lisonge** [comment]
![image](https://github.com/lisonge/vite-plugin-monkey/assets/38517192/529f49f3-6533-4f2b-81a6-c72e998e0652)

我这边没问题

**Comment by lisonge** [comment]
另外，你使用的 `html-minifier-terser` 在 `vite serve` 下不能工作

![image](https://github.com/lisonge/vite-plugin-monkey/assets/38517192/fe1afeb4-b303-4dba-bb86-bcbeef087e3b)

使用 `vite-plugin-node-polyfills` 可以解决这个问题

![image](https://github.com/lisonge/vite-plugin-monkey/assets/38517192/df5f2be1-a195-4f6e-9726-a1bb6c2ac7ad)

**Comment by Sec-ant** [comment]
> ![image](https://user-images.githubusercontent.com/38517192/250295984-529f49f3-6533-4f2b-81a6-c72e998e0652.png)
> 
> 我这边没问题

不好意思我检查了一下是 CSP 配置的问题，按照 https://github.com/lisonge/vite-plugin-monkey/issues/1 修改后就可以了

> 另外，你使用的 `html-minifier-terser` 在 `vite serve` 下不能工作
> 
> ![image](https://user-images.githubusercontent.com/38517192/250299016-fe1afeb4-b303-4dba-bb86-bcbeef087e3b.png)
> 
> 使用 `vite-plugin-node-polyfills` 可以解决这个问题
> 
> ![image](https://user-images.githubusercontent.com/38517192/250298997-df5f2be1-a195-4f6e-9726-a1bb6c2ac7ad.png)

谢谢，已通过安装这个插件解决！
