### ISSUE TITLE
GM_getClipboard获取剪切板内容是不支持使用吗？

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [lisonge/vite-plugin-monkey#94]
![image](https://github.com/lisonge/vite-plugin-monkey/assets/59086082/11e1d50e-4c12-41af-8aae-86f03b66422f)

**Comment by lisonge** [comment]
```ts
import { monkeyWindow } from '$';

console.log(monkeyWindow.GM_getClipboard);
console.log(monkeyWindow.your_want_any_api);
```

**Comment by pingfangdeguang** [comment]
> ```ts
> import { monkeyWindow } from '$';
> 
> console.log(monkeyWindow.GM_getClipboard);
> console.log(monkeyWindow.your_want_any_api);
> ```

好的，我之前是这样引入的
import { GM_cookie, unsafeWindow, monkeyWindow, GM_addElement, GM_getValue, GM_setValue, GM_setClipboard } from '$';  

然后只有GM_getClipboard会报错

**Comment by lisonge** [comment]
这种只能引入提前声明好的 GM_api ，`GM_getClipboard` 是哪个脚本引擎提供的方法? 我没找到文档

**Comment by pingfangdeguang** [comment]
> 是哪个脚本引擎提

感谢大佬解答，这个我也不清楚，我用的时候问的gpt, 油猴和脚本猫是都有这个方法的，我也不知道在哪里

**Comment by lisonge** [comment]
并没有这个方法

![image](https://github.com/lisonge/vite-plugin-monkey/assets/38517192/5319fe3d-70a1-4f9d-a3f2-e5a0ec1dbbbd)

**Comment by duoluodexiaoxiaoyuan** [comment]
> 并没有这个方法
> 
> ![image](https://user-images.githubusercontent.com/38517192/251889812-5319fe3d-70a1-4f9d-a3f2-e5a0ec1dbbbd.png)
> 
> 只有 GM_setClipboard 方法
> 
> https://www.tampermonkey.net/documentation.php#api:GM_setClipboard

那应该是脚本猫独有的

**Comment by lisonge** [comment]
脚本猫的 文档 和 源码 里都没有 `GM_getClipboard`

**Comment by duoluodexiaoxiaoyuan** [comment]
> 脚本猫的 文档 和 源码 里都没有 `GM_getClipboard`

我刚才本地写了脚本测试了一下确实不行，可能记错了，尴尬
